import { BUNDLED_ENGINE_ASSETS } from "../assets.ts";
import { MisoUsageError } from "../core/errors.ts";
import { MSB1_CONTROL, MSB1_CONTROL_BYTES, createMsb1Ring } from "./pcm-ring.ts";
import type { Msb1RingLayout } from "./pcm-ring.ts";
export type PcmFeedOperation = "moduleLoad"|"nodeCreate"|"attachPost"|"readyTimeout"|"closed";
export class PcmFeedError extends Error { readonly operation:PcmFeedOperation; constructor(operation:PcmFeedOperation,message:string,cause?:unknown){super(message,{cause});this.name="PcmFeedError";this.operation=operation} }
export interface FeedPort { postMessage(message:unknown):void }
export interface FeedNode { readonly port:FeedPort; disconnect():void }
export interface FeedContext { readonly audioWorklet:{addModule(url:string):Promise<void>} }
export interface FeedNodeOptions { readonly numberOfInputs:number; readonly numberOfOutputs:number }
export interface FeedOptions { readonly context:FeedContext; readonly sources:readonly Msb1RingLayout[]; readonly quantumFrames:number; readonly capacityChunks?:number; readonly moduleUrl?:string|URL; readonly createNode?:(context:FeedContext,name:string,options:FeedNodeOptions)=>FeedNode }
export interface EngineFeed { readonly rings:readonly SharedArrayBuffer[]; readonly state:"pending"|"active"|"closed"; ready(options?:{readonly timeoutMs?:number;readonly now?:()=>number;readonly wait?:(ms:number)=>Promise<void>}):Promise<void>; close():void }
export async function prepareEngineFeed(context:FeedContext,moduleUrl:string|URL=BUNDLED_ENGINE_ASSETS.pcmFeedWorklet):Promise<void>{try{await context.audioWorklet.addModule(String(moduleUrl))}catch(e){throw new PcmFeedError("moduleLoad","PCM feed worklet prelude could not load",e)}}
export function attachEngineFeed(options:FeedOptions):EngineFeed {if(!Number.isSafeInteger(options.quantumFrames)||options.quantumFrames<=0)throw new MisoUsageError("quantumFrames must be a positive integer");const rings=options.sources.map(s=>createMsb1Ring({...s,frameCapacity:options.quantumFrames,capacity:options.capacityChunks??64}));let node:FeedNode;try{node=options.createNode?.(options.context,"miso-sab-feed-attach",{numberOfInputs:0,numberOfOutputs:1})??defaultNode(options.context)}catch(e){release(rings);throw new PcmFeedError("nodeCreate","Engine feed attach processor is unavailable",e)}let state:"pending"|"active"|"closed"=rings.length===0?"active":"pending";const close=()=>{if(state==="closed")return;state="closed";release(rings);try{node.port.postMessage({op:"detach"})}catch{}try{node.disconnect()}catch{}};try{node.port.postMessage({op:"attach",rings})}catch(e){close();throw new PcmFeedError("attachPost","Engine feed attach message could not be posted",e)}return{rings,get state(){return state},async ready(settings={}){if(state==="closed")throw new PcmFeedError("closed","Engine feed is closed");if(state==="active")return;const now=settings.now??(()=>Date.now()),wait=settings.wait??(ms=>new Promise<void>(r=>setTimeout(r,ms))),deadline=now()+(settings.timeoutMs??2000);while(state==="pending"){if(rings.every(attached)){state="active";return}if(now()>=deadline){close();throw new PcmFeedError("readyTimeout","Engine feed attach confirmation timed out")}await wait(0)}if(state==="closed")throw new PcmFeedError("closed","Engine feed is closed")},close}}
 function release(rings:readonly SharedArrayBuffer[]){for(const ring of rings)Atomics.store(new Int32Array(ring,0,MSB1_CONTROL_BYTES/4),MSB1_CONTROL.WRITER_STATE,0)} function attached(r:SharedArrayBuffer){return Atomics.load(new Int32Array(r,0,32),MSB1_CONTROL.ATTACHED)===1} function defaultNode(context:FeedContext):FeedNode{const C=(globalThis as unknown as {AudioWorkletNode?:new(context:unknown,name:string,options:FeedNodeOptions)=>FeedNode}).AudioWorkletNode;if(C===undefined)throw new Error("AudioWorkletNode is unavailable");return new C(context,"miso-sab-feed-attach",{numberOfInputs:0,numberOfOutputs:1})}
