// Private prepared-control owner shared by browser and headless control paths.
//
// The semantic input is always the already encoded command block. This module deliberately has no
// wire encoder: one command shape, generated by the host/SDK, is decoded here and carried through
// preparation and admission unchanged.

function structure(layout, name) {
  const value = layout?.structures?.[name] ?? layout?.[name];
  if (value === undefined) throw new Error(`missing generated ABI structure ${name}`);
  return value;
}

function field(layout, structureName, fieldName) {
  const row = structure(layout, structureName).fields?.find((item) => item.name === fieldName);
  if (row === undefined) throw new Error(`missing generated ABI field ${structureName}.${fieldName}`);
  return row.offset;
}

function arrayLength(layout, structureName, fieldName) {
  const row = structure(layout, structureName).fields?.find((item) => item.name === fieldName);
  const match = row?.type?.match(/\[(\d+)\]$/);
  if (match === undefined || match === null) throw new Error(`missing generated ABI array ${structureName}.${fieldName}`);
  return Number(match[1]);
}

function constant(layout, group, name) {
  const row = layout?.constants?.[group]?.find?.((item) => item.name === name);
  if (row === undefined) throw new Error(`missing generated ABI constant ${group}.${name}`);
  return row.value;
}

function scalarConstant(layout, name) {
  const value = layout?.constants?.[name];
  if (!Number.isSafeInteger(value)) throw new Error(`missing generated ABI scalar ${name}`);
  return value;
}

function schemaOf(layout) {
  if (layout === undefined || layout === null) throw new Error("prepared-control requires ABI_LAYOUT");
  const commandRecord = layout.commandRecord;
  if (commandRecord?.fields === undefined) throw new Error("missing generated ABI commandRecord");
  const command = Object.fromEntries(commandRecord.fields.map((item) => [item.name, item.offset]));
  for (const name of ["kind", "rack", "channel", "trackIndex", "effectIndex", "parameterId", "values"]) {
    if (!Number.isSafeInteger(command[name])) throw new Error(`missing generated ABI command field ${name}`);
  }
  const valueCount = arrayLength(layout, "eqTargetConfig", "values");
  return Object.freeze({
    abiVersion: layout.abiVersion,
    validResults: new Set(layout.constants?.resultCodes?.map?.((item) => item.value) ?? []),
    resultOk: constant(layout, "resultCodes", "ok"),
    resultInvalid: constant(layout, "resultCodes", "invalidArgument"),
    resultWrongState: constant(layout, "resultCodes", "wrongState"),
    resultBackpressure: constant(layout, "resultCodes", "backpressure"),
    reasonBackpressure: constant(layout, "commandReasons", "backpressure"),
    resultUnsupported: constant(layout, "resultCodes", "unsupported"),
    resultInternal: constant(layout, "resultCodes", "internal"),
    resultReprepare: constant(layout, "resultCodes", "reprepareRequired"),
    effectParamKind: constant(layout, "wireCommandKinds", "effectParam"),
    maximumCommandRecords: scalarConstant(layout, "maximumCommandRecords"),
    command: Object.freeze({
      bytes: commandRecord.bytes,
      kind: command.kind,
      rack: command.rack,
      channel: command.channel,
      trackIndex: command.trackIndex,
      effectIndex: command.effectIndex,
      parameterId: command.parameterId,
      values: command.values,
      valueCount: arrayLength({ structures: { commandRecord } }, "commandRecord", "values"),
    }),
    valueCount,
    request: Object.freeze({
      bytes: structure(layout, "eqTargetRequest").bytes,
      structSize: field(layout, "eqTargetRequest", "structSize"),
      abiVersion: field(layout, "eqTargetRequest", "abiVersion"),
      sampleRate: field(layout, "eqTargetRequest", "sampleRateHz"),
      seedCount: field(layout, "eqTargetRequest", "seedCount"),
      editCount: field(layout, "eqTargetRequest", "editCount"),
      reserved: field(layout, "eqTargetRequest", "reserved"),
      values: structure(layout, "eqTargetRequest").bytes,
      editBytes: structure(layout, "eqTargetEdit").bytes,
      editOffset: structure(layout, "eqTargetRequest").bytes + valueCount * 4,
      editParameterId: field(layout, "eqTargetEdit", "parameterId"),
      editChannel: field(layout, "eqTargetEdit", "channel"),
      editValue: field(layout, "eqTargetEdit", "value"),
    }),
    result: Object.freeze({
      headerBytes: structure(layout, "eqTargetResult").bytes,
      structSize: field(layout, "eqTargetResult", "structSize"),
      abiVersion: field(layout, "eqTargetResult", "abiVersion"),
      valueCount: field(layout, "eqTargetResult", "valueCount"),
      targetCount: field(layout, "eqTargetResult", "targetCount"),
      values: structure(layout, "eqTargetResult").bytes,
    }),
    target: Object.freeze({
      bytes: structure(layout, "preparedEffectTarget").bytes,
      slot: field(layout, "preparedEffectTarget", "slot"),
      channel: field(layout, "preparedEffectTarget", "channel"),
      words: field(layout, "preparedEffectTarget", "words"),
      wordCount: arrayLength(layout, "preparedEffectTarget", "words"),
    }),
    config: Object.freeze({
      bytes: structure(layout, "eqTargetConfig").bytes,
      structSize: field(layout, "eqTargetConfig", "structSize"),
      abiVersion: field(layout, "eqTargetConfig", "abiVersion"),
      sampleRate: field(layout, "eqTargetConfig", "sampleRateHz"),
      valueCount: field(layout, "eqTargetConfig", "valueCount"),
      generation: field(layout, "eqTargetConfig", "hostGeneration"),
      revision: field(layout, "eqTargetConfig", "ownerRevision"),
      values: field(layout, "eqTargetConfig", "values"),
    }),
    companion: Object.freeze({
      headerBytes: structure(layout, "preparedEffectCompanionHeader").bytes,
      structSize: field(layout, "preparedEffectCompanionHeader", "structSize"),
      abiVersion: field(layout, "preparedEffectCompanionHeader", "abiVersion"),
      generation: field(layout, "preparedEffectCompanionHeader", "hostGeneration"),
      targetCount: field(layout, "preparedEffectCompanionHeader", "targetCount"),
      reserved: field(layout, "preparedEffectCompanionHeader", "reserved"),
      recordBytes: structure(layout, "preparedEffectCompanionRecord").bytes,
      trackIndex: field(layout, "preparedEffectCompanionRecord", "trackIndex"),
      rack: field(layout, "preparedEffectCompanionRecord", "rack"),
      effectIndex: field(layout, "preparedEffectCompanionRecord", "effectIndex"),
      recordReserved: field(layout, "preparedEffectCompanionRecord", "reserved"),
      revision: field(layout, "preparedEffectCompanionRecord", "baseRevision"),
      slot: field(layout, "preparedEffectCompanionRecord", "slot"),
      channel: field(layout, "preparedEffectCompanionRecord", "channel"),
      words: field(layout, "preparedEffectCompanionRecord", "words"),
    }),
  });
}

function failure(result, requestId = 0, extra = undefined) {
  return Object.freeze(extra === undefined
    ? { tag: "miso.error.v1", requestId, result }
    : { tag: "miso.error.v1", requestId, result, ...extra });
}

function sameBytes(left, right) {
  if (!(left instanceof Uint8Array) || left.byteLength !== right.byteLength) return false;
  for (let index = 0; index < right.byteLength; index += 1) if (left[index] !== right[index]) return false;
  return true;
}

function keyOf(address) {
  return `${address.trackIndex}/${address.rack}/${address.effectIndex}`;
}

function checkedU64(value, positive = false) {
  if (typeof value !== "bigint" || value < (positive ? 1n : 0n) || value > 0xffffffffffffffffn) {
    throw new Error("invalid u64");
  }
  return value;
}

function decodeCommands(records, count, schema) {
  if (!(records instanceof Uint8Array) || !Number.isSafeInteger(count) || count <= 0
      || count > schema.maximumCommandRecords || records.byteLength !== count * schema.command.bytes) {
    throw failure(schema.resultInvalid);
  }
  const view = new DataView(records.buffer, records.byteOffset, records.byteLength);
  const rows = [];
  for (let index = 0; index < count; index += 1) {
    const offset = index * schema.command.bytes;
    const values = [];
    for (let valueIndex = 0; valueIndex < schema.command.valueCount; valueIndex += 1) {
      values.push(view.getFloat32(offset + schema.command.values + valueIndex * 4, true));
    }
    rows.push({
      index,
      kind: view.getUint8(offset + schema.command.kind),
      rack: view.getUint8(offset + schema.command.rack),
      channel: view.getUint8(offset + schema.command.channel),
      trackIndex: view.getUint32(offset + schema.command.trackIndex, true),
      effectIndex: view.getUint32(offset + schema.command.effectIndex, true),
      parameterId: view.getUint32(offset + schema.command.parameterId, true),
      values,
    });
  }
  return rows;
}

function readConfig(bytes, sampleRateHz, schema) {
  if (!(bytes instanceof Uint8Array) || bytes.byteLength !== schema.config.bytes) throw failure(schema.resultInternal);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (view.getUint32(schema.config.structSize, true) !== schema.config.bytes
      || view.getUint32(schema.config.abiVersion, true) !== schema.abiVersion
      || view.getUint32(schema.config.sampleRate, true) !== sampleRateHz
      || view.getUint32(schema.config.valueCount, true) !== schema.valueCount) throw failure(schema.resultInternal);
  let generation;
  let revision;
  try {
    generation = checkedU64(view.getBigUint64(schema.config.generation, true), true);
    revision = checkedU64(view.getBigUint64(schema.config.revision, true));
  } catch (_) { throw failure(schema.resultInternal); }
  const values = new Float32Array(schema.valueCount);
  for (let index = 0; index < values.length; index += 1) {
    values[index] = view.getFloat32(schema.config.values + index * 4, true);
    if (!Number.isFinite(values[index])) throw failure(schema.resultInternal);
  }
  return { generation, revision, values };
}

function readPreparationResult(exports, memory, schema) {
  const pointer = exports.miso_engine_web_v1_eq_target_result_ptr();
  const bytes = exports.miso_engine_web_v1_eq_target_result_bytes();
  const capacity = exports.miso_engine_web_v1_eq_target_result_capacity();
  if (!Number.isSafeInteger(pointer) || pointer <= 0 || !Number.isSafeInteger(bytes)
      || !Number.isSafeInteger(capacity) || bytes < schema.result.headerBytes || bytes > capacity
      || pointer + bytes > memory.buffer.byteLength) throw failure(schema.resultInternal);
  const view = new DataView(memory.buffer, pointer, bytes);
  const valueCount = view.getUint32(schema.result.valueCount, true);
  const targetCount = view.getUint32(schema.result.targetCount, true);
  const targetOffset = schema.result.headerBytes + schema.valueCount * 4;
  const maximumTargets = Math.floor((capacity - targetOffset) / schema.target.bytes);
  if (view.getUint32(schema.result.structSize, true) !== schema.result.headerBytes
      || view.getUint32(schema.result.abiVersion, true) !== schema.abiVersion
      || valueCount !== schema.valueCount || targetCount > maximumTargets
      || targetOffset + targetCount * schema.target.bytes !== bytes) throw failure(schema.resultInternal);
  const values = new Float32Array(schema.valueCount);
  for (let index = 0; index < values.length; index += 1) {
    values[index] = view.getFloat32(schema.result.values + index * 4, true);
    if (!Number.isFinite(values[index])) throw failure(schema.resultInternal);
  }
  const targets = [];
  for (let index = 0; index < targetCount; index += 1) {
    const offset = targetOffset + index * schema.target.bytes;
    const words = new Uint32Array(schema.target.wordCount);
    for (let word = 0; word < words.length; word += 1) {
      words[word] = view.getUint32(offset + schema.target.words + word * 4, true);
    }
    targets.push({
      slot: view.getUint32(offset + schema.target.slot, true),
      channel: view.getUint32(offset + schema.target.channel, true),
      words,
    });
  }
  return { values, targets };
}

function buildRequest(exports, memory, sampleRateHz, values, edits, schema) {
  const pointer = exports.miso_engine_web_v1_eq_target_request_ptr();
  const capacity = exports.miso_engine_web_v1_eq_target_request_capacity();
  const bytes = schema.request.editOffset + edits.length * schema.request.editBytes;
  if (!Number.isSafeInteger(pointer) || pointer <= 0 || !Number.isSafeInteger(capacity)
      || bytes > capacity || pointer + bytes > memory.buffer.byteLength) throw failure(schema.resultInternal);
  const view = new DataView(memory.buffer, pointer, bytes);
  view.setUint32(schema.request.structSize, schema.request.bytes, true);
  view.setUint32(schema.request.abiVersion, schema.abiVersion, true);
  view.setUint32(schema.request.sampleRate, sampleRateHz, true);
  view.setUint32(schema.request.seedCount, schema.valueCount, true);
  view.setUint32(schema.request.editCount, edits.length, true);
  for (let index = 0; index < 3; index += 1) view.setUint32(schema.request.reserved + index * 4, 0, true);
  values.forEach((value, index) => view.setFloat32(schema.request.values + index * 4, value, true));
  edits.forEach((edit, index) => {
    const offset = schema.request.editOffset + index * schema.request.editBytes;
    view.setUint32(offset + schema.request.editParameterId, edit.parameterId, true);
    view.setUint32(offset + schema.request.editChannel, edit.channel, true);
    view.setFloat32(offset + schema.request.editValue, edit.value, true);
  });
  return bytes;
}

function buildCompanion(generation, owners, schema) {
  const targetCount = owners.reduce((sum, owner) => sum + owner.prepared.targets.length, 0);
  if (targetCount > 2 * schema.maximumCommandRecords) throw failure(schema.resultBackpressure);
  const payload = new Uint8Array(schema.companion.headerBytes + targetCount * schema.companion.recordBytes);
  const view = new DataView(payload.buffer);
  view.setUint32(schema.companion.structSize, schema.companion.headerBytes, true);
  view.setUint32(schema.companion.abiVersion, schema.abiVersion, true);
  view.setBigUint64(schema.companion.generation, generation, true);
  view.setUint32(schema.companion.targetCount, targetCount, true);
  view.setUint32(schema.companion.reserved, 0, true);
  let index = 0;
  for (const owner of owners) for (const target of owner.prepared.targets) {
    const offset = schema.companion.headerBytes + index * schema.companion.recordBytes;
    view.setUint32(offset + schema.companion.trackIndex, owner.address.trackIndex, true);
    view.setUint32(offset + schema.companion.rack, owner.address.rack, true);
    view.setUint32(offset + schema.companion.effectIndex, owner.address.effectIndex, true);
    view.setUint32(offset + schema.companion.recordReserved, 0, true);
    view.setBigUint64(offset + schema.companion.revision, owner.revision, true);
    view.setUint32(offset + schema.companion.slot, target.slot, true);
    view.setUint32(offset + schema.companion.channel, target.channel, true);
    target.words.forEach((word, wordIndex) =>
      view.setUint32(offset + schema.companion.words + wordIndex * 4, word, true));
    index += 1;
  }
  return payload;
}

function instanceWorkspace(instance, schema) {
  const exports = instance?.exports ?? instance;
  if (typeof exports?.miso_engine_web_v1_eq_target_open !== "function") {
    return { available: false, failure: failure(schema.resultInternal) };
  }
  const result = exports.miso_engine_web_v1_eq_target_open();
  if (result === schema.resultUnsupported) return { available: false };
  if (result !== schema.resultOk || !(exports.memory instanceof WebAssembly.Memory)) {
    return { available: false, failure: failure(schema.resultInternal) };
  }
  return { available: true, instance, exports, memory: exports.memory };
}

/** Construct the private browser/headless prepared-control owner. */
export function createPreparedControl(options) {
  const schema = schemaOf(options?.abiLayout);
  const owners = new Map();
  let workspace = options.instance === undefined ? null : instanceWorkspace(options.instance, schema);
  let generation = 0n;
  let epoch = 0;
  let pending = null;
  let disposed = false;

  function ensureWorkspace() {
    if (workspace !== null) return workspace;
    try {
      workspace = options.module instanceof WebAssembly.Module
        ? instanceWorkspace(new WebAssembly.Instance(options.module, {}), schema)
        : { available: false, failure: failure(schema.resultInternal) };
    } catch (_) {
      workspace = { available: false, failure: failure(schema.resultInternal) };
    }
    return workspace;
  }

  function invalidate(addresses = undefined) {
    epoch += 1;
    if (addresses === undefined) owners.clear();
    else for (const address of addresses) owners.delete(keyOf(address));
    generation = 0n;
  }

  function checkEpoch(token) {
    if (disposed || token !== epoch) throw failure(schema.resultWrongState);
  }

  function acceptConfig(address, bytes) {
    const config = readConfig(bytes, options.sampleRateHz, schema);
    if (generation !== 0n && generation !== config.generation) {
      invalidate();
      throw failure(schema.resultWrongState);
    }
    generation = config.generation;
    const owner = {
      status: "prepared", address, generation: config.generation,
      revision: config.revision, values: config.values,
    };
    owners.set(keyOf(address), owner);
    return owner;
  }

  function loadOwnerSync(address) {
    const cached = owners.get(keyOf(address));
    if (cached !== undefined) return cached;
    const active = ensureWorkspace();
    if (!active.available) {
      if (active.failure !== undefined) throw active.failure;
      return { status: "ordinary", address };
    }
    if (typeof options.configCopySync !== "function") throw failure(schema.resultWrongState);
    const reply = options.configCopySync(address);
    if (reply?.result === schema.resultUnsupported) {
      const ordinary = { status: "ordinary", address }; owners.set(keyOf(address), ordinary); return ordinary;
    }
    if (reply?.result === schema.resultInvalid && Number.isSafeInteger(reply.reason)) {
      return { status: "refusal", address, result: reply.result, reason: reply.reason };
    }
    if (reply?.result !== schema.resultOk) throw failure(reply?.result ?? schema.resultInternal, reply?.requestId ?? 0);
    return acceptConfig(address, reply.config);
  }

  async function loadOwner(address, token) {
    const cached = owners.get(keyOf(address));
    if (cached !== undefined) return cached;
    const active = ensureWorkspace();
    if (!active.available) {
      if (active.failure !== undefined) throw active.failure;
      return { status: "ordinary", address };
    }
    if (typeof options.configCopy !== "function") throw failure(schema.resultWrongState);
    const reply = await options.configCopy(address);
    checkEpoch(token);
    if (reply?.result === schema.resultUnsupported) {
      const ordinary = { status: "ordinary", address }; owners.set(keyOf(address), ordinary); return ordinary;
    }
    if (reply?.result === schema.resultInvalid && Number.isSafeInteger(reply.reason)) {
      return { status: "refusal", address, result: reply.result, reason: reply.reason };
    }
    if (reply?.result !== schema.resultOk) throw failure(reply?.result ?? schema.resultInternal, reply?.requestId ?? 0);
    return acceptConfig(address, reply.config);
  }

  function prepareOwner(owner, group) {
    const active = ensureWorkspace();
    if (!active.available) throw active.failure ?? failure(schema.resultUnsupported);
    const edits = group.rows.map((row) => ({
      parameterId: row.parameterId, channel: row.channel, value: row.values[0],
    }));
    const requestBytes = buildRequest(active.exports, active.memory, options.sampleRateHz, owner.values, edits, schema);
    const result = active.exports.miso_engine_web_v1_eq_target_prepare(requestBytes);
    if (result !== schema.resultOk) {
      const localIndex = active.exports.miso_engine_web_v1_eq_target_rejected_edit_index();
      const rejectedEditIndex = Number.isSafeInteger(localIndex) && localIndex < group.rows.length
        ? group.rows[localIndex].index : undefined;
      const reason = active.exports.miso_engine_web_v1_eq_target_rejected_reason();
      if (rejectedEditIndex === undefined) invalidate();
      return { refusal: true, result, reason, rejectedEditIndex };
    }
    return { owner, prepared: readPreparationResult(active.exports, active.memory, schema) };
  }

  function begin(records, count) {
    if (disposed) throw failure(schema.resultWrongState);
    const rows = decodeCommands(records, count, schema);
    const original = records.slice();
    const transfer = records.slice();
    const groups = new Map();
    for (const row of rows) {
      if (row.kind !== schema.effectParamKind) continue;
      const address = { trackIndex: row.trackIndex, rack: row.rack, effectIndex: row.effectIndex };
      const key = keyOf(address);
      const group = groups.get(key) ?? (groups.set(key, { address, rows: [] }), groups.get(key));
      group.rows.push(row);
    }
    if (groups.size === 0) return { ordinary: true, transfer, count };
    const active = ensureWorkspace();
    if (!active.available) {
      if (active.failure !== undefined) throw active.failure;
      return { ordinary: true, transfer, count };
    }
    if ([...groups.keys()].every((key) => owners.get(key)?.status === "ordinary")) {
      return { ordinary: true, transfer, count };
    }
    if (pending !== null) return {
      original, count, refusal: {
        result: schema.resultBackpressure, reason: schema.reasonBackpressure, rejectedEditIndex: 0,
      },
    };
    const token = epoch;
    pending = { token };
    return { ordinary: false, original, transfer, count, groups, token };
  }

  function localRefusal(state, refusal) {
    if (disposed) throw failure(schema.resultWrongState);
    if (typeof options.preparedRefusal !== "function") throw failure(schema.resultInternal);
    return options.preparedRefusal(
      state.original,
      state.count,
      refusal.reason,
      refusal.rejectedEditIndex,
      refusal.result,
    );
  }

  function localRefusalSync(state, refusal) {
    if (disposed) throw failure(schema.resultWrongState);
    const callback = options.preparedRefusalSync ?? options.preparedRefusal;
    if (typeof callback !== "function") throw failure(schema.resultInternal);
    return callback(
      state.original,
      state.count,
      refusal.reason,
      refusal.rejectedEditIndex,
      refusal.result,
    );
  }

  function prepareSync(state) {
    const preparedOwners = [];
    for (const group of state.groups.values()) {
      const owner = loadOwnerSync(group.address);
      if (owner.status === "refusal") {
        return { refusal: { ...owner, rejectedEditIndex: group.rows[0]?.index ?? 0 } };
      }
      if (owner.status !== "prepared") continue;
      if (owner.revision === 0xffffffffffffffffn) return { refusal: {
        result: schema.resultBackpressure, reason: schema.reasonBackpressure,
        rejectedEditIndex: group.rows[0].index,
      } };
      const prepared = prepareOwner(owner, group);
      if (prepared.refusal !== undefined) return { refusal: prepared };
      preparedOwners.push({ ...prepared, address: owner.address, revision: owner.revision });
    }
    if (preparedOwners.length === 0) return { preparedOwners, nextRevisions: [], companion: null };
    const nextRevisions = preparedOwners.map((owner) => {
      return owner.revision + 1n;
    });
    return { preparedOwners, nextRevisions, companion: buildCompanion(generation, preparedOwners, schema) };
  }

  async function prepareAsync(state) {
    const preparedOwners = [];
    for (const group of state.groups.values()) {
      checkEpoch(state.token);
      const owner = await loadOwner(group.address, state.token);
      checkEpoch(state.token);
      if (owner.status === "refusal") {
        return { refusal: { ...owner, rejectedEditIndex: group.rows[0]?.index ?? 0 } };
      }
      if (owner.status !== "prepared") continue;
      if (owner.revision === 0xffffffffffffffffn) return { refusal: {
        result: schema.resultBackpressure, reason: schema.reasonBackpressure,
        rejectedEditIndex: group.rows[0].index,
      } };
      const prepared = prepareOwner(owner, group);
      if (prepared.refusal !== undefined) return { refusal: prepared };
      preparedOwners.push({ ...prepared, address: owner.address, revision: owner.revision });
    }
    if (preparedOwners.length === 0) return { preparedOwners, nextRevisions: [], companion: null };
    const nextRevisions = preparedOwners.map((owner) => {
      return owner.revision + 1n;
    });
    return { preparedOwners, nextRevisions, companion: buildCompanion(generation, preparedOwners, schema) };
  }

  function validAck(reply, count, original) {
    return reply !== null && typeof reply === "object" && Number.isSafeInteger(reply.result)
      && schema.validResults.has(reply.result)
      && Number.isSafeInteger(reply.admitted) && reply.admitted >= 0 && reply.admitted <= count
      && reply.records instanceof Uint8Array && reply.records.byteLength === original.byteLength
      && sameBytes(reply.records, original)
      && (reply.result === schema.resultOk ? reply.admitted === count : reply.admitted === 0);
  }

  function commit(preparedOwners, nextRevisions) {
    for (let index = 0; index < preparedOwners.length; index += 1) {
      const owner = preparedOwners[index];
      const current = owners.get(keyOf(owner.address));
      if (current?.status !== "prepared") throw failure(schema.resultWrongState);
      current.values = owner.prepared.values.slice();
      current.revision = nextRevisions[index];
    }
  }

  function finish(reply, state, prepared) {
    if (!validAck(reply, state.count, state.original)) {
      invalidate();
      throw failure(schema.resultInternal, reply?.requestId ?? 0);
    }
    if (reply.result === schema.resultWrongState || reply.result === schema.resultInternal
        || reply.result === schema.resultReprepare) {
      invalidate();
      throw failure(reply.result, reply.requestId ?? 0);
    }
    if (reply.result === schema.resultOk) commit(prepared.preparedOwners, prepared.nextRevisions);
    return reply;
  }

  async function submit(records, count) {
    let state;
    try { state = begin(records, count); } catch (cause) { return Promise.reject(cause); }
    if (state.refusal !== undefined) return localRefusal(state, state.refusal);
    if (state.ordinary) return options.ordinarySubmit(state.transfer, state.count);
    const run = async () => {
      const prepared = await prepareAsync(state);
      if (prepared.refusal !== undefined) return localRefusal(state, prepared.refusal);
      checkEpoch(state.token);
      if (prepared.preparedOwners.length === 0) return options.ordinarySubmit(state.transfer, state.count);
      const reply = await options.preparedSubmit(state.transfer, prepared.companion, state.count);
      checkEpoch(state.token);
      return finish(reply, state, prepared);
    };
    return run().catch((cause) => {
      if (cause?.tag !== "miso.error.v1" || cause.result === schema.resultInternal
          || cause.result === schema.resultWrongState || cause.result === schema.resultReprepare) invalidate();
      throw cause;
    }).finally(() => { if (pending?.token === state.token) pending = null; });
  }

  function submitSync(records, count) {
    const state = begin(records, count);
    if (state.refusal !== undefined) return localRefusalSync(state, state.refusal);
    if (state.ordinary) return options.ordinarySubmitSync(state.transfer, state.count);
    try {
      const prepared = prepareSync(state);
      if (prepared.refusal !== undefined) return localRefusalSync(state, prepared.refusal);
      if (prepared.preparedOwners.length === 0) return options.ordinarySubmitSync(state.transfer, state.count);
      return finish(
        options.preparedSubmitSync(state.transfer, prepared.companion, state.count), state, prepared,
      );
    } catch (cause) {
      invalidate();
      throw cause;
    } finally { if (pending?.token === state.token) pending = null; }
  }

  function close() {
    if (disposed) return;
    disposed = true;
    invalidate();
    if (workspace?.available) {
      try { workspace.exports.miso_engine_web_v1_eq_target_close(); } catch (_) { /* terminal */ }
    }
    workspace = null;
  }

  return Object.freeze({
    submit,
    submitSync,
    close,
    invalidate,
    get available() { return ensureWorkspace().available; },
  });
}
