import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const RESULTS_PATH = path.join(HERE, "results.json");
const MATRIX_PATH = path.join(path.dirname(HERE), "BROWSER_DEPLOYMENT_MATRIX.md");

export function renderMatrix(results) {
  const rows = results.browsers.map((row) => {
    const gates = row.gates;
    return `| ${row.browser} | ${row.versionFloor} | ${row.outcome} | ${gates.attestation} | ${gates.audioWorkletBoot} | ${gates.nativeCorpusDigest} | ${gates.mainThreadStall} |`;
  }).join("\n");
  return `<!-- Generated by qualification/generate-matrix.mjs from qualification/results.json. -->
# Browser deployment matrix

This matrix is generated from the pinned Playwright ${results.playwrightVersion} headless Linux qualification run over the single shipped simd128 AudioWorklet artifact. The version shown is the lowest version qualified by this run; older versions are unqualified, not implicitly supported.

| Browser engine | Qualified version floor | Attestation outcome | SIMD gate | AudioWorklet boot | Native corpus digest | 100 ms main-thread stall |
| --- | --- | --- | --- | --- | --- | --- |
${rows}

The stall gate injects at least ${results.minimumStallMs} ms of main-realm blocking after prefilling the ${results.defaultRingFrames}-frame default source ring. It requires bit-exact, dropout-free, frame-aligned output. \`miso.unsupported.v1\` is the only qualified refusal for a browser without simd128.

Playwright's browser builds are qualification targets, not claims about branded Chrome, Safari, or untested Firefox builds. Re-run the matrix before lowering a deployment floor or changing Playwright. This work does not qualify cross-origin isolation or shared-memory operation.
`;
}

async function main() {
  const results = JSON.parse(await readFile(RESULTS_PATH, "utf8"));
  const rendered = renderMatrix(results);
  if (process.argv.includes("--check")) {
    const existing = await readFile(MATRIX_PATH, "utf8");
    if (existing !== rendered) throw new Error("browser deployment matrix is stale");
  } else {
    await writeFile(MATRIX_PATH, rendered);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
