import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const RESULTS_PATH = path.join(HERE, "results.json");
const MATRIX_PATH = path.join(path.dirname(HERE), "BROWSER_DEPLOYMENT_MATRIX.md");

export function renderMatrix(results) {
  const rows = results.browsers.map((row) => {
    const gates = row.gates;
    return `| ${row.browser} | ${row.versionFloor} | ${row.outcome} | ${gates.attestation} | ${gates.audioWorkletBoot} | ${gates.nativeCorpusDigest} | ${gates.controlPath} | ${gates.observation} | ${gates.mainThreadStall} |`;
  }).join("\n");
  return `<!-- Generated by qualification/generate-matrix.mjs from qualification/results.json. -->
# Browser deployment matrix

This matrix is generated from the pinned Playwright ${results.playwrightVersion} headless Linux qualification run over candidate \`${results.candidateCommit}\` and the single shipped simd128 AudioWorklet artifact \`${results.wasmSha256}\`. The version shown is the lowest version qualified by this run; older versions are unqualified, not implicitly supported.

| Browser engine | Qualified version floor | Attestation outcome | SIMD gate | AudioWorklet boot | Native corpus digest | Live console (#137) | Observation (#143) | 100 ms main-thread stall |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
${rows}

The observation gate (issue #143) subscribes to the compressor's declared gain-reduction tap, requires at least one \`miso.meter.v1\` frame whose \`trackGrDb\` carries a **positive** magnitude the app can read without clamping, requires \`masterGrDb\` to be the designated track's own reading, requires the reported windows to advance monotonically and tile with no gap, requires an unsubscribe to actually stop the traffic, and requires the armed and unarmed renders of the same sixteen blocks to produce **bit-identical audio** -- arming a declared tap may not move a sample. The live-console gate (issue #137) applies one \`miso.command.v1\` matrix retarget, requires the rendered output to equal the declared half-gain result bit for bit, and requires at least one decimated \`miso.meter.v1\` frame whose master peak is a real observation of that output plus at least one windowed \`miso.telemetry.v1\` frame. The stall gate injects at least ${results.minimumStallMs} ms of main-realm blocking after prefilling the ${results.defaultRingFrames}-frame default source ring, now with the control path and the meter fold both live across the fault, and requires bit-exact, dropout-free, frame-aligned output. \`miso.unsupported.v1\` is the only qualified refusal for a browser without simd128.

Playwright's browser builds are qualification targets, not claims about branded Chrome, Safari, or untested Firefox builds. Re-run the matrix before lowering a deployment floor or changing Playwright. This work does not qualify cross-origin isolation or shared-memory operation.
`;
}

async function main() {
  const results = JSON.parse(await readFile(RESULTS_PATH, "utf8"));
  const rendered = renderMatrix(results);
  if (process.argv.includes("--check")) {
    const existing = await readFile(MATRIX_PATH, "utf8");
    if (existing !== rendered) throw new Error("browser deployment matrix is stale");
  } else {
    await writeFile(MATRIX_PATH, rendered);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
