#![allow(clippy::disallowed_methods)] // identity gate for the sealed fast-dB caller

//! Gate M2 — `exp2_lane` and `log2_lane` produce identical bits at every lane width.
//!
//! The scalar `impl Lane for f32` is the oracle (master plan §3.2): a width-N result must be the
//! scalar result computed lane by lane, bit for bit, never within a tolerance. That is what makes
//! the determinism claim (D5) hold when a bank runs at width 4 or 8 on one host and width 1 on
//! another.
//!
//! This is a different statement from gate M1. M1 says the polynomial is accurate; M2 says the
//! width does not change the answer. A correct-but-width-dependent implementation passes M1 and
//! fails here, which is exactly the failure a `wide` operand-order slip would produce.
//!
//! Both functions are built from `Lane` trait operations only — `mul`, `add`, `sub`, `gt`,
//! `select`, `floor`, `min`, `max`, `exp2_int`, `frexp` — so 83a's gate G1 already proves each
//! operation individually. M2 proves the composition, over a corpus that includes the inputs G1's
//! per-operation pools do not reach in this combination: the fold boundaries, the clamp rails and
//! the `sqrt(2)` mantissa split.
//!
//! The pinned digest is generated by the scalar instantiation, so 83d can replay it under
//! wasmtime as part of G5/M3 without needing a native run to compare against.

use lane::{Lane, Simd4, Simd8};
use sha2::{Digest, Sha256};

/// Number of inputs in the identity corpus.
const POINTS: usize = 1 << 20;

/// SHA-256 of the scalar `exp2_lane` results over the corpus, pinned on x86_64.
const EXP2_DIGEST: [u8; 32] = [
    70, 134, 247, 228, 121, 115, 151, 247, 219, 150, 250, 28, 4, 225, 107, 233, 182, 216, 178, 120,
    108, 25, 194, 186, 235, 35, 111, 192, 208, 199, 35, 186,
];

/// SHA-256 of the scalar `log2_lane` results over the corpus, pinned on x86_64.
const LOG2_DIGEST: [u8; 32] = [
    193, 84, 220, 45, 185, 14, 76, 152, 18, 81, 207, 148, 211, 122, 142, 94, 17, 113, 182, 106, 65,
    141, 162, 223, 158, 106, 211, 60, 167, 103, 199, 56,
];

/// Xorshift64\*, the same generator the lane gates use, so the corpora are comparable.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Self(if seed == 0 {
            0x9e37_79b9_7f4a_7c15
        } else {
            seed
        })
    }

    fn next_u32(&mut self) -> u32 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        (x.wrapping_mul(0x2545_f491_4f6c_dd1d) >> 32) as u32
    }
}

/// The identity corpus: the interesting boundaries first, then a seeded mixture of raw bit
/// patterns (NaN, infinity, subnormals — the clamp has to handle them) and moderate values.
fn corpus() -> Vec<f32> {
    let mut values = vec![
        0.0,
        -0.0,
        1.0,
        -1.0,
        // exp2 fold boundary and its neighbourhood.
        0.5,
        -0.5,
        f32::from_bits(0.5_f32.to_bits() - 1),
        f32::from_bits(0.5_f32.to_bits() + 1),
        1.5,
        -1.5,
        2.5,
        -2.5,
        // exp2 clamp rails.
        -126.0,
        127.0,
        -127.0,
        128.0,
        1.0e30,
        -1.0e30,
        f32::INFINITY,
        f32::NEG_INFINITY,
        f32::NAN,
        -f32::NAN,
        // log2 mantissa fold at sqrt(2), and its neighbourhood.
        core::f32::consts::SQRT_2,
        f32::from_bits(core::f32::consts::SQRT_2.to_bits() - 1),
        f32::from_bits(core::f32::consts::SQRT_2.to_bits() + 1),
        // log2 clamp rail and the subnormal band below it.
        f32::MIN_POSITIVE,
        f32::from_bits(f32::MIN_POSITIVE.to_bits() - 1),
        f32::from_bits(1),
        f32::MAX,
        f32::MIN,
        // The dB range the conversions actually carry.
        -120.0,
        -6.0,
        6.0,
        24.0,
    ];

    let mut rng = Rng::new(0x4d31_5341_5448_0001);
    let mut index = 0;
    while values.len() < POINTS {
        let bits = rng.next_u32();
        let value = if index % 2 == 0 {
            f32::from_bits(bits)
        } else {
            // A moderate exponent: the shape audio carries, where a raw sweep is mostly NaN.
            let mantissa = bits & 0x007f_ffff;
            let exponent = ((bits >> 23) % 60) as i32 - 30 + 127;
            f32::from_bits((bits & 0x8000_0000) | ((exponent as u32) << 23) | mantissa)
        };
        values.push(value);
        index += 1;
    }

    // Pad to a multiple of the widest lane count.
    while !values.len().is_multiple_of(8) {
        values.push(0.0);
    }
    values
}

/// Apply a lane function at width `L::WIDTH` across `input`, collecting result bits.
fn apply<L: Lane>(input: &[f32], function: fn(L) -> L) -> Vec<u32> {
    let mut out = vec![0u32; input.len()];
    let mut offset = 0;
    while offset < input.len() {
        let value = L::load(&input[offset..]);
        function(value).store_bits(&mut out[offset..]);
        offset += L::WIDTH;
    }
    out
}

fn digest(bits: &[u32]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    for word in bits {
        hasher.update(word.to_le_bytes());
    }
    hasher.finalize().into()
}

fn hex(bytes: &[u8; 32]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Compare width 4 and width 8 against the scalar oracle, bit for bit.
fn compare_widths(
    name: &str,
    input: &[f32],
    scalar: fn(f32) -> f32,
    wide4: fn(Simd4) -> Simd4,
    wide8: fn(Simd8) -> Simd8,
) -> Vec<u32> {
    let oracle = apply::<f32>(input, scalar);
    let four = apply::<Simd4>(input, wide4);
    let eight = apply::<Simd8>(input, wide8);

    for (index, ((&want, &got4), &got8)) in
        oracle.iter().zip(four.iter()).zip(eight.iter()).enumerate()
    {
        assert_eq!(
            got4, want,
            "{name}: width 4 differs from the scalar oracle at input {} ({:?}): {got4:#010x} vs \
             {want:#010x}",
            index, input[index]
        );
        assert_eq!(
            got8, want,
            "{name}: width 8 differs from the scalar oracle at input {} ({:?}): {got8:#010x} vs \
             {want:#010x}",
            index, input[index]
        );
    }

    oracle
}

/// Compare width 4 and width 8 against the scalar oracle, then check the scalar digest.
fn check(
    name: &str,
    input: &[f32],
    scalar: fn(f32) -> f32,
    wide4: fn(Simd4) -> Simd4,
    wide8: fn(Simd8) -> Simd8,
    pinned: &[u8; 32],
) {
    let oracle = compare_widths(name, input, scalar, wide4, wide8);

    let actual = digest(&oracle);
    if std::env::var_os("MISO_ENGINE_MATH_PIN").is_some() {
        println!("{name} digest: {:?}", actual);
        return;
    }
    assert_eq!(
        actual,
        *pinned,
        "{name}: scalar digest {} does not match the pin {}; a change here is a change to rendered \
         bits and needs the master plan §8 fixture procedure, not a re-pin",
        hex(&actual),
        hex(pinned)
    );
}

/// Inputs whose clamp treatment is the load-bearing premise of LANE-4.
fn exp2_caller_edges() -> Vec<f32> {
    let mut values = vec![
        f32::from_bits(0x7fc0_0000),
        f32::from_bits(0x7fc0_0001),
        f32::from_bits(0xffc0_0000),
        f32::INFINITY,
        f32::NEG_INFINITY,
        0.0,
        -0.0,
        f32::from_bits(0x0000_0001),
        f32::from_bits(0x8000_0001),
        f32::from_bits(0x007f_ffff),
        f32::from_bits(0x807f_ffff),
        f32::MIN_POSITIVE,
        -f32::MIN_POSITIVE,
    ];
    for boundary in [-127.0_f32, -126.0, 126.0, 127.0] {
        let bits = boundary.to_bits();
        values.push(f32::from_bits(bits - 1));
        values.push(boundary);
        values.push(f32::from_bits(bits + 1));
    }
    while !values.len().is_multiple_of(8) {
        values.push(0.0);
    }
    values
}

#[test]
fn m2_exp2_callers_directed_edges_are_lane_identical() {
    let input = exp2_caller_edges();
    compare_widths(
        "fast_gain_from_db directed edges",
        &input,
        math::fast_db::fast_gain_from_db::<f32>,
        math::fast_db::fast_gain_from_db::<Simd4>,
        math::fast_db::fast_gain_from_db::<Simd8>,
    );
    compare_widths(
        "exp2_lane directed edges",
        &input,
        math::exp2_lane::<f32>,
        math::exp2_lane::<Simd4>,
        math::exp2_lane::<Simd8>,
    );
}

#[test]
fn m2_exp2_lane_identity() {
    let input = corpus();
    check(
        "exp2_lane",
        &input,
        math::exp2_lane::<f32>,
        math::exp2_lane::<Simd4>,
        math::exp2_lane::<Simd8>,
        &EXP2_DIGEST,
    );
}

#[test]
fn m2_log2_lane_identity() {
    let input = corpus();
    check(
        "log2_lane",
        &input,
        math::log2_lane::<f32>,
        math::log2_lane::<Simd4>,
        math::log2_lane::<Simd8>,
        &LOG2_DIGEST,
    );
}

/// The corpus must reach the branches that make M2 worth running: both sides of the `exp2` fold,
/// both clamp rails, and both sides of the `log2` mantissa split.
#[test]
fn m2_corpus_reaches_every_branch() {
    let input = corpus();

    let folded = input
        .iter()
        .filter(|x| x.is_finite() && (*x - x.floor()) > 0.5)
        .count();
    let unfolded = input
        .iter()
        .filter(|x| x.is_finite() && (*x - x.floor()) <= 0.5)
        .count();
    assert!(folded > 1000, "only {folded} inputs take the exp2 fold");
    assert!(unfolded > 1000, "only {unfolded} inputs skip the exp2 fold");

    let over = input.iter().filter(|x| **x > 127.0).count();
    let under = input.iter().filter(|x| **x < -126.0).count();
    assert!(
        over > 100 && under > 100,
        "clamp rails: {over} over, {under} under"
    );

    let positive_normal: Vec<f32> = input
        .iter()
        .copied()
        .filter(|x| *x > 0.0 && x.is_finite() && !x.is_subnormal())
        .collect();
    let (mut high, mut low) = (0usize, 0usize);
    for x in positive_normal {
        let mantissa = f32::from_bits((x.to_bits() & 0x807f_ffff) | (127 << 23));
        if mantissa > core::f32::consts::SQRT_2 {
            high += 1;
        } else {
            low += 1;
        }
    }
    assert!(
        high > 1000 && low > 1000,
        "log2 mantissa split: {high} above sqrt(2), {low} below"
    );

    let nan = input.iter().filter(|x| x.is_nan()).count();
    assert!(
        nan > 100,
        "only {nan} NaN inputs; the clamp behaviour would go unchecked"
    );
}
