[package]
name = "miso-engine-host-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
miso-engine-target-smoke.workspace = true

[[bin]]
name = "miso_engine_host_native"
path = "src/main.rs"

[features]
default = []

[lints]
workspace = true
