//! The cross-target determinism corpus behind gate M3.
//!
//! Each case is one function evaluated over a fixed, seed-generated million-point input set. The
//! inputs are produced by integer arithmetic only (a xorshift64\* generator), so every target
//! builds the identical input sequence; the outputs are therefore a pure function of the vendored
//! scalar layer. `tests/m3_digests.rs` hashes each case's output words and compares against
//! [`M3_DIGESTS`], and job 83d replays the same cases under wasmtime against the same pins.
//!
//! No case can produce a NaN: the determinism claim (master plan D5) excludes NaN payloads because
//! wasm canonicalises them, so the input filters keep every case's output NaN-free
//! (`log`-family inputs are forced non-negative, `pow` bases are forced positive, and the
//! remaining functions map every finite input to a non-NaN result).
//!
//! The pinned digests are a regression guard, not an oracle. They were generated by the scalar
//! layer on x86_64; correctness of the layer itself is what `tests/scalar_accuracy.rs` proves.

use crate::{
    atan, atan2, cos, cosf, db_to_gain, db_to_gain_f32, exp, exp2, exp2f, expf, expm1, expm1f,
    floor, floorf, gain_to_db, gain_to_db_f32, log, log2, log2f, log10, log10f, logf, pow, powf,
    sin, sinf, sqrt, sqrtf, tan, tanf, tanh, tanhf,
};

/// Number of input points in every corpus case.
pub const POINTS: usize = 1_000_000;

/// Number of corpus cases.
pub const CASE_COUNT: usize = 32;

/// Human-readable name of each corpus case, indexed by case number.
pub const CASE_NAMES: [&str; CASE_COUNT] = [
    "exp",
    "exp2",
    "expm1",
    "log",
    "log2",
    "log10",
    "pow",
    "sin",
    "cos",
    "tan",
    "tanh",
    "atan",
    "atan2",
    "expf",
    "exp2f",
    "expm1f",
    "logf",
    "log2f",
    "log10f",
    "powf",
    "sinf",
    "cosf",
    "tanf",
    "tanhf",
    "sqrt",
    "sqrtf",
    "floor",
    "floorf",
    "db_to_gain",
    "gain_to_db",
    "db_to_gain_f32",
    "gain_to_db_f32",
];

/// xorshift64\* state. Integer-only, so identical on every target.
struct Rng(u64);

impl Rng {
    fn new(case: usize) -> Self {
        // Any odd seed works; mixing the case index keeps the cases independent.
        Self(0x9e37_79b9_7f4a_7c15 ^ ((case as u64).wrapping_mul(0x0002_5a2f_1c3d_0b41) | 1))
    }

    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }
}

/// Finite `f64` from arbitrary bits: an infinite or NaN exponent field is pulled down one bit.
fn finite_f64(bits: u64) -> f64 {
    let bits = if (bits >> 52) & 0x7ff == 0x7ff {
        bits & !(1u64 << 62)
    } else {
        bits
    };
    f64::from_bits(bits)
}

/// Finite `f32` from arbitrary bits; see [`finite_f64`].
fn finite_f32(bits: u32) -> f32 {
    let bits = if (bits >> 23) & 0xff == 0xff {
        bits & !(1u32 << 30)
    } else {
        bits
    };
    f32::from_bits(bits)
}

/// Edge inputs prepended to every `f64` case, before the generated points.
const EDGE_F64: [f64; 16] = [
    0.0,
    -0.0,
    1.0,
    -1.0,
    0.5,
    -0.5,
    2.0,
    -2.0,
    f64::MIN_POSITIVE,
    -f64::MIN_POSITIVE,
    f64::MAX,
    f64::MIN,
    core::f64::consts::PI,
    core::f64::consts::FRAC_PI_2,
    core::f64::consts::E,
    core::f64::consts::LN_2,
];

/// Edge inputs prepended to every `f32` case, before the generated points.
const EDGE_F32: [f32; 16] = [
    0.0,
    -0.0,
    1.0,
    -1.0,
    0.5,
    -0.5,
    2.0,
    -2.0,
    f32::MIN_POSITIVE,
    -f32::MIN_POSITIVE,
    f32::MAX,
    f32::MIN,
    core::f32::consts::PI,
    core::f32::consts::FRAC_PI_2,
    core::f32::consts::E,
    core::f32::consts::LN_2,
];

/// Whether case `case` is an `f32` case (its result words are `f32::to_bits` widened to `u64`).
fn is_f32_case(case: usize) -> bool {
    matches!(case, 13..=23 | 25 | 27 | 30 | 31)
}

/// Run corpus case `case`, writing one result word per input into `out`.
///
/// `f64` results are stored as `f64::to_bits`, `f32` results as `f32::to_bits` widened to `u64`.
///
/// # Panics
///
/// Panics if `case >= CASE_COUNT` or `out.len() != POINTS`.
pub fn run_case(case: usize, out: &mut [u64]) {
    assert!(case < CASE_COUNT, "corpus case out of range");
    assert_eq!(
        out.len(),
        POINTS,
        "corpus output buffer must hold POINTS words"
    );

    let mut rng = Rng::new(case);
    let f32_case = is_f32_case(case);

    for (index, slot) in out.iter_mut().enumerate() {
        let (x, y) = if f32_case {
            let x = if index < EDGE_F32.len() {
                EDGE_F32[index]
            } else {
                finite_f32((rng.next() >> 32) as u32)
            };
            let y = finite_f32((rng.next() >> 32) as u32);
            (f64::from(x), f64::from(y))
        } else {
            let x = if index < EDGE_F64.len() {
                EDGE_F64[index]
            } else {
                finite_f64(rng.next())
            };
            let y = finite_f64(rng.next());
            (x, y)
        };

        // `y` is consumed unconditionally above so that every case walks the generator in lockstep;
        // single-argument cases simply ignore it.
        *slot = eval(case, x, y);
    }
}

/// Evaluate one corpus point. `x` is the primary input, `y` the second argument of the two-argument
/// cases. `f32` cases narrow their inputs back to `f32` before calling.
fn eval(case: usize, x: f64, y: f64) -> u64 {
    let xf = x as f32;
    let yf = y as f32;
    match case {
        0 => exp(x).to_bits(),
        1 => exp2(x).to_bits(),
        2 => expm1(x).to_bits(),
        3 => log(x.abs()).to_bits(),
        4 => log2(x.abs()).to_bits(),
        5 => log10(x.abs()).to_bits(),
        // A positive base keeps `pow` NaN-free for every finite exponent.
        6 => pow(x.abs() + f64::MIN_POSITIVE, y).to_bits(),
        7 => sin(x).to_bits(),
        8 => cos(x).to_bits(),
        9 => tan(x).to_bits(),
        10 => tanh(x).to_bits(),
        11 => atan(x).to_bits(),
        12 => atan2(x, y).to_bits(),
        13 => u64::from(expf(xf).to_bits()),
        14 => u64::from(exp2f(xf).to_bits()),
        15 => u64::from(expm1f(xf).to_bits()),
        16 => u64::from(logf(xf.abs()).to_bits()),
        17 => u64::from(log2f(xf.abs()).to_bits()),
        18 => u64::from(log10f(xf.abs()).to_bits()),
        19 => u64::from(powf(xf.abs() + f32::MIN_POSITIVE, yf).to_bits()),
        20 => u64::from(sinf(xf).to_bits()),
        21 => u64::from(cosf(xf).to_bits()),
        22 => u64::from(tanf(xf).to_bits()),
        23 => u64::from(tanhf(xf).to_bits()),
        24 => sqrt(x.abs()).to_bits(),
        25 => u64::from(sqrtf(xf.abs()).to_bits()),
        26 => floor(x).to_bits(),
        27 => u64::from(floorf(xf).to_bits()),
        28 => db_to_gain(x).to_bits(),
        29 => gain_to_db(x.abs()).to_bits(),
        30 => u64::from(db_to_gain_f32(xf).to_bits()),
        31 => u64::from(gain_to_db_f32(xf.abs()).to_bits()),
        _ => unreachable!(),
    }
}

/// SHA-256 of each corpus case's result words, little-endian, pinned from the x86_64 scalar run.
///
/// Job 83d re-checks these under wasmtime for the wasm32 target; any difference is a
/// cross-target determinism failure, never something to re-pin.
pub const M3_DIGESTS: [[u8; 32]; CASE_COUNT] = [[0; 32]; CASE_COUNT];
