[package]
name = "miso-engine-stem-publisher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "miso_engine_stem_publisher"

[dependencies]
flacenc.workspace = true
miso-engine-flac-decoder.workspace = true
miso-engine-source.workspace = true
miso-engine-stem-hasher.workspace = true

[dev-dependencies]
sha2.workspace = true

[lints]
workspace = true
