#!/usr/bin/env node
/**
 * Deterministically transcribe Phase 0's checked JSON artifacts into TypeScript data modules.
 *
 * This generator deliberately has no engine-specific table of effects, parameters, ABI offsets,
 * reasons, or assets. The three Phase 0 documents are the only data authority. `--check` compares
 * the byte-for-byte expected modules with the checked-in copies, so a manual generated edit fails
 * before a consumer can observe drift.
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const sdkRoot = resolve(here, "..");
const assets = resolve(sdkRoot, "assets");
const generated = resolve(sdkRoot, "src", "generated");

const inputs = [
  ["catalog", "miso-engine-v2-parameter-metadata.json", "CATALOG"],
  ["abi", "miso-engine-v2-abi-layout.json", "ABI_LAYOUT"],
  ["provenance", "miso-engine-v2.provenance.json", "PROVENANCE"],
];

function usage() {
  throw new Error("usage: node sdk/codegen/generate.mjs [--check]");
}

function deepFreezeSource() {
  return `function deepFreeze<T>(value: T): T {\n`
    + `  if (value !== null && typeof value === "object") {\n`
    + `    Object.freeze(value);\n`
    + `    for (const child of Object.values(value as Record<string, unknown>)) {\n`
    + `      deepFreeze(child);\n`
    + `    }\n`
    + `  }\n`
    + `  return value;\n`
    + `}\n\n`;
}

function moduleTypes(kind, symbol) {
  if (kind === "catalog") {
    return `export type Catalog = typeof ${symbol};\n`
      + `export type BuiltinParameter = Catalog["builtins"]["parameters"][number];\n`
      + `export type EffectDescriptor = Catalog["effects"][number];\n`
      + `export type EffectId = EffectDescriptor["id"];\n`
      + `export type EffectParameter<E extends EffectId> = Extract<EffectDescriptor, { readonly id: E }>["parameters"][number];\n`
      + `export type EffectParameterName<E extends EffectId> = EffectParameter<E>["name"];\n`
      + `export type EffectObservation<E extends EffectId> = Extract<EffectDescriptor, { readonly id: E }>["observations"][number];\n`
      + `export type TapName<E extends EffectId> = EffectObservation<E>["name"];\n`
      + `export type CommandReasonName = Catalog["commandReasons"][number]["name"];\n`
      + `export type ObservationTransactionKindName = Catalog["observationTransactionKinds"][number]["name"];\n`;
  }
  if (kind === "abi") {
    return `export type AbiLayout = typeof ${symbol};\n`
      + `export type AbiStructureName = keyof AbiLayout["structures"];\n`
      + `export type AbiConstantGroup = keyof AbiLayout["constants"];\n`
      + `export type AbiCommandField = AbiLayout["commandRecord"]["fields"][number];\n`;
  }
  return `export type Provenance = typeof ${symbol};\n`
    + `export type ProvenanceAssetName = keyof Provenance["assets"];\n`;
}

function renderModule(kind, sourceName, symbol, value) {
  const json = JSON.stringify(value, null, 2);
  return `// @generated by sdk/codegen/generate.mjs from sdk/assets/${sourceName}; DO NOT EDIT.\n`
    + `// The source JSON is canonical Phase 0 data. Types below are derived from this value.\n\n`
    + deepFreezeSource()
    + `export const ${symbol} = deepFreeze(\n${json} as const,\n);\n\n`
    + moduleTypes(kind, symbol);
}

async function expectedModules() {
  return Promise.all(inputs.map(async ([kind, sourceName, symbol]) => {
    const path = resolve(assets, sourceName);
    let parsed;
    try {
      parsed = JSON.parse(await readFile(path, "utf8"));
    } catch (error) {
      throw new Error(`cannot read valid JSON input ${path}: ${error.message}`);
    }
    return [resolve(generated, `${kind}.ts`), renderModule(kind, sourceName, symbol, parsed)];
  }));
}

async function run(check) {
  const modules = await expectedModules();
  let stale = false;
  for (const [path, expected] of modules) {
    if (check) {
      let actual;
      try {
        actual = await readFile(path, "utf8");
      } catch (error) {
        console.error(`sdk codegen: missing generated module ${path}: ${error.message}`);
        stale = true;
        continue;
      }
      if (actual !== expected) {
        console.error(`sdk codegen: stale generated module ${path}; run npm run codegen in sdk/`);
        stale = true;
      }
    } else {
      await writeFile(path, expected, "utf8");
      console.log(`wrote ${path}`);
    }
  }
  if (stale) process.exitCode = 1;
}

const args = process.argv.slice(2);
if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) usage();
await run(args[0] === "--check");
