//! The cross-target determinism corpus behind gate M3.
//!
//! Each case is one function evaluated over a fixed, seed-generated million-point input set. The
//! inputs are produced by integer arithmetic and exact conversions only, so every target builds an
//! identical input sequence; the outputs are therefore a pure function of the vendored scalar
//! layer. `tests/m3_determinism.rs` hashes each case's output words and compares them against
//! [`M3_DIGESTS`], and job 83d replays the same cases under wasmtime against the same pins.
//!
//! **Sampling.** A uniformly random `f64` *bit pattern* has a uniformly random exponent, so it is
//! almost always astronomically large or astronomically small. A corpus built that way would feed
//! `exp2` nothing but its overflow and underflow early-outs and would not notice a wrong
//! polynomial coefficient at all (measured: a corpus of raw bit patterns misses a one-ulp change
//! to `exp2`'s leading coefficient entirely). Each case therefore samples the domain where its
//! function does real work, while every fourth point stays a raw finite bit pattern so subnormals,
//! the representable extremes and huge trig arguments remain covered.
//!
//! **No NaN.** The determinism claim (master plan D5) excludes NaN payloads because wasm
//! canonicalises them, so the input filters keep every case NaN-free: `log`-family inputs are
//! non-negative, `pow` bases are positive, and every other function maps finite inputs to non-NaN
//! results. `tests/m3_determinism.rs::m3_corpus_is_nan_free` is the guard.
//!
//! The pinned digests are a regression guard, not an oracle. They were generated by this layer on
//! x86_64; correctness of the layer itself is what `tests/scalar_accuracy.rs` proves.

use crate::{
    atan, atan2, cos, cosf, db_to_gain, db_to_gain_f32, exp, exp2, exp2f, expf, expm1, expm1f,
    floor, floorf, gain_to_db, gain_to_db_f32, log, log2, log2f, log10, log10f, logf, pow, powf,
    sin, sinf, sqrt, sqrtf, tan, tanf, tanh, tanhf,
};

/// Number of input points in every corpus case.
pub const POINTS: usize = 1_000_000;

/// Number of corpus cases.
pub const CASE_COUNT: usize = 32;

/// Human-readable name of each corpus case, indexed by case number.
pub const CASE_NAMES: [&str; CASE_COUNT] = [
    "exp",
    "exp2",
    "expm1",
    "log",
    "log2",
    "log10",
    "pow",
    "sin",
    "cos",
    "tan",
    "tanh",
    "atan",
    "atan2",
    "expf",
    "exp2f",
    "expm1f",
    "logf",
    "log2f",
    "log10f",
    "powf",
    "sinf",
    "cosf",
    "tanf",
    "tanhf",
    "sqrt",
    "sqrtf",
    "floor",
    "floorf",
    "db_to_gain",
    "gain_to_db",
    "db_to_gain_f32",
    "gain_to_db_f32",
];

/// xorshift64\* state. Integer-only, so identical on every target.
struct Rng(u64);

impl Rng {
    fn new(case: usize) -> Self {
        // Any odd seed works; mixing the case index keeps the cases independent.
        Self(0x9e37_79b9_7f4a_7c15 ^ ((case as u64).wrapping_mul(0x0002_5a2f_1c3d_0b41) | 1))
    }

    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }
}

/// Finite `f64` from arbitrary bits: an infinite or NaN exponent field is pulled down one bit.
fn finite_f64(bits: u64) -> f64 {
    let bits = if (bits >> 52) & 0x7ff == 0x7ff {
        bits & !(1u64 << 62)
    } else {
        bits
    };
    f64::from_bits(bits)
}

/// Edge inputs prepended to every case, before the generated points.
const EDGE: [f64; 16] = [
    0.0,
    -0.0,
    1.0,
    -1.0,
    0.5,
    -0.5,
    2.0,
    -2.0,
    f64::MIN_POSITIVE,
    -f64::MIN_POSITIVE,
    f64::MAX,
    f64::MIN,
    core::f64::consts::PI,
    core::f64::consts::FRAC_PI_2,
    core::f64::consts::E,
    core::f64::consts::LN_2,
];

/// Whether case `case` is an `f32` case (its result words are `f32::to_bits` widened to `u64`).
fn is_f32_case(case: usize) -> bool {
    matches!(case, 13..=23 | 25 | 27 | 30 | 31)
}

/// The `f64` case a case shares its input domain with; the `f32` cases mirror their `f64`
/// counterparts so both halves of the corpus cover the same shapes.
fn domain_of(case: usize) -> usize {
    match case {
        13..=23 => case - 13,
        25 => 24,
        27 => 26,
        30 => 28,
        31 => 29,
        other => other,
    }
}

/// Uniform `[0, 1)` from a bit pattern. Converting a 53-bit integer to `f64` is exact, so this is
/// the same value on every target.
fn unit(bits: u64) -> f64 {
    ((bits >> 11) as f64) / 9_007_199_254_740_992.0
}

/// `2^k` built straight from the exponent field, so the input sampler never calls the layer whose
/// outputs it is generating. `k` is truncated from `n`.
fn pow2(n: f64) -> f64 {
    let k = n as i32;
    if k >= -1022 {
        f64::from_bits(((k + 1023) as u64) << 52)
    } else {
        let shift = (-1022 - k) as u32;
        if shift > 52 {
            0.0
        } else {
            f64::from_bits(1u64 << (52 - shift))
        }
    }
}

/// One input for `case`, from two uniform deviates. See the module note on sampling.
///
/// `narrow` selects the `f32` variant of the domain: `expf` saturates at about +/-88 where `exp`
/// runs to +/-709, so sharing one range would push nine tenths of the `f32` points into the
/// saturation branches.
fn domain_sample(case: usize, narrow: bool, u: f64, v: f64) -> f64 {
    // Log-uniform over a range of binades, with a full mantissa: `pow2` alone would yield only a
    // few hundred distinct inputs.
    let log_uniform = |lo: f64, span: f64| pow2(lo + u * span) * (1.0 + v);

    match domain_of(case) {
        // exp: the whole non-trivial range, a little past both saturation thresholds.
        0 if narrow => -100.0 + u * 195.0,
        0 => -760.0 + u * 1480.0,
        // exp2
        1 if narrow => -155.0 + u * 290.0,
        1 => -1090.0 + u * 2130.0,
        // expm1: past the point where the result is just `exp(x)` or `-1`.
        2 if narrow => -20.0 + u * 110.0,
        2 => -40.0 + u * 750.0,
        // log, log2, log10, sqrt, gain_to_db: log-uniform over the positive range.
        3..=5 | 24 | 29 if narrow => log_uniform(-150.0, 278.0),
        3..=5 | 24 | 29 => log_uniform(-1070.0, 2093.0),
        // pow / powf: `eval` uses one draw as the base and one as the exponent.
        6 if narrow => -30.0 + u * 60.0,
        6 => -40.0 + u * 80.0,
        // sin, cos, tan: a few hundred radians, the medium argument-reduction path.
        7..=9 => -200.0 + u * 400.0,
        // tanh: `f32` cannot resolve neighbouring results much past +/-3 (the spacing of `f32`
        // near 1 is 6e-8 and tanh's slope there is 1e-2), so the narrow domain stops there and
        // the raw-bit quarter of the corpus covers saturation.
        10 if narrow => -3.0 + u * 6.0,
        10 => -19.0 + u * 38.0,
        // atan, atan2
        11 | 12 => -50.0 + u * 100.0,
        // floor
        26 if narrow => -1.0e6 + u * 2.0e6,
        26 => -1.0e7 + u * 2.0e7,
        // db_to_gain: the dB range a mixer actually uses, widened past both rails.
        28 if narrow => -160.0 + u * 200.0,
        28 => -400.0 + u * 500.0,
        _ => unreachable!(),
    }
}

/// Narrow to `f32`, saturating to the largest finite `f32` rather than to an infinity.
///
/// Without this, an `f64` edge value such as `f64::MAX` would become `f32::INFINITY`, and
/// `sinf(inf)` is NaN, which the corpus must not contain.
fn narrow_finite(x: f64) -> f32 {
    let v = x as f32;
    if v.is_finite() {
        v
    } else if v > 0.0 {
        f32::MAX
    } else {
        f32::MIN
    }
}

/// Run corpus case `case`, writing one result word per input into `out`.
///
/// `f64` results are stored as `f64::to_bits`, `f32` results as `f32::to_bits` widened to `u64`.
///
/// # Panics
///
/// Panics if `case >= CASE_COUNT` or `out.len() != POINTS`.
pub fn run_case(case: usize, out: &mut [u64]) {
    assert!(case < CASE_COUNT, "corpus case out of range");
    assert_eq!(
        out.len(),
        POINTS,
        "corpus output buffer must hold POINTS words"
    );

    let mut rng = Rng::new(case);
    let narrow = is_f32_case(case);

    for (index, slot) in out.iter_mut().enumerate() {
        // Four draws per point regardless of arity, so every case walks the generator in lockstep.
        let a = rng.next();
        let b = rng.next();
        let c = rng.next();
        let d = rng.next();

        let (mut x, mut y) = if index < EDGE.len() {
            (EDGE[index], EDGE[EDGE.len() - 1 - index])
        } else if index % 4 == 0 {
            // Raw finite bit patterns: subnormals, the extremes, huge trig arguments.
            (finite_f64(a), finite_f64(c))
        } else {
            (
                domain_sample(case, narrow, unit(a), unit(b)),
                domain_sample(case, narrow, unit(c), unit(d)),
            )
        };

        if narrow {
            x = f64::from(narrow_finite(x));
            y = f64::from(narrow_finite(y));
        }

        *slot = eval(case, x, y);
    }
}

/// Evaluate one corpus point. `x` is the primary input, `y` the second argument of the two-argument
/// cases; `f32` cases narrow both back to `f32` before calling.
fn eval(case: usize, x: f64, y: f64) -> u64 {
    let xf = x as f32;
    let yf = y as f32;
    match case {
        0 => exp(x).to_bits(),
        1 => exp2(x).to_bits(),
        2 => expm1(x).to_bits(),
        3 => log(x.abs()).to_bits(),
        4 => log2(x.abs()).to_bits(),
        5 => log10(x.abs()).to_bits(),
        // A strictly positive base keeps `pow` NaN-free for every finite exponent.
        6 => pow(x.abs() + f64::MIN_POSITIVE, y * 0.5).to_bits(),
        7 => sin(x).to_bits(),
        8 => cos(x).to_bits(),
        9 => tan(x).to_bits(),
        10 => tanh(x).to_bits(),
        11 => atan(x).to_bits(),
        12 => atan2(x, y).to_bits(),
        13 => u64::from(expf(xf).to_bits()),
        14 => u64::from(exp2f(xf).to_bits()),
        15 => u64::from(expm1f(xf).to_bits()),
        16 => u64::from(logf(xf.abs()).to_bits()),
        17 => u64::from(log2f(xf.abs()).to_bits()),
        18 => u64::from(log10f(xf.abs()).to_bits()),
        19 => u64::from(powf(xf.abs() + f32::MIN_POSITIVE, yf * 0.5).to_bits()),
        20 => u64::from(sinf(xf).to_bits()),
        21 => u64::from(cosf(xf).to_bits()),
        22 => u64::from(tanf(xf).to_bits()),
        23 => u64::from(tanhf(xf).to_bits()),
        24 => sqrt(x.abs()).to_bits(),
        25 => u64::from(sqrtf(xf.abs()).to_bits()),
        26 => floor(x).to_bits(),
        27 => u64::from(floorf(xf).to_bits()),
        28 => db_to_gain(x).to_bits(),
        29 => gain_to_db(x.abs()).to_bits(),
        30 => u64::from(db_to_gain_f32(xf).to_bits()),
        31 => u64::from(gain_to_db_f32(xf.abs()).to_bits()),
        _ => unreachable!(),
    }
}

/// SHA-256 of each corpus case's result words, little-endian, pinned from the x86_64 scalar run.
///
/// Job 83d re-checks these under wasmtime for the wasm32 target; any difference is a
/// cross-target determinism failure, never something to re-pin.
pub const M3_DIGESTS: [[u8; 32]; CASE_COUNT] = [
    // exp
    [
        220, 95, 214, 4, 176, 180, 128, 222, 188, 116, 130, 78, 204, 249, 23, 243, 11, 229, 79,
        198, 76, 226, 150, 242, 60, 73, 96, 128, 33, 160, 160, 165,
    ],
    // exp2
    [
        229, 66, 24, 156, 132, 174, 105, 39, 203, 131, 12, 75, 184, 203, 224, 93, 178, 70, 50, 103,
        210, 227, 21, 62, 35, 90, 131, 54, 104, 153, 123, 146,
    ],
    // expm1
    [
        240, 37, 233, 120, 29, 239, 206, 192, 97, 60, 152, 139, 36, 97, 208, 54, 251, 155, 169, 48,
        247, 230, 76, 62, 189, 222, 190, 141, 156, 4, 213, 99,
    ],
    // log
    [
        180, 35, 37, 227, 190, 252, 196, 36, 16, 187, 53, 210, 165, 0, 231, 253, 4, 190, 32, 52,
        92, 161, 136, 121, 210, 168, 0, 203, 238, 101, 55, 163,
    ],
    // log2
    [
        178, 244, 16, 217, 11, 108, 117, 18, 164, 58, 204, 83, 186, 144, 178, 231, 169, 134, 220,
        20, 121, 230, 154, 202, 104, 191, 118, 104, 235, 2, 67, 144,
    ],
    // log10
    [
        187, 34, 149, 150, 216, 161, 28, 253, 66, 73, 220, 1, 191, 33, 175, 146, 63, 34, 249, 93,
        1, 42, 227, 106, 186, 220, 141, 7, 182, 129, 213, 87,
    ],
    // pow
    [
        177, 90, 71, 147, 166, 79, 144, 200, 215, 214, 199, 132, 77, 122, 9, 211, 19, 131, 88, 232,
        50, 242, 205, 27, 92, 75, 61, 94, 208, 203, 24, 82,
    ],
    // sin
    [
        15, 234, 176, 205, 236, 14, 141, 241, 239, 248, 155, 128, 127, 72, 176, 33, 243, 166, 126,
        42, 219, 111, 141, 4, 133, 142, 30, 117, 243, 219, 51, 252,
    ],
    // cos
    [
        232, 148, 142, 141, 153, 46, 186, 144, 155, 84, 100, 242, 232, 126, 119, 66, 195, 93, 67,
        10, 207, 47, 173, 213, 120, 158, 184, 174, 67, 78, 182, 197,
    ],
    // tan
    [
        124, 26, 101, 140, 242, 230, 45, 13, 246, 250, 250, 176, 124, 196, 119, 100, 229, 140, 157,
        61, 230, 221, 191, 226, 130, 237, 224, 115, 19, 19, 78, 159,
    ],
    // tanh
    [
        62, 240, 89, 98, 37, 134, 223, 196, 53, 37, 193, 160, 103, 252, 103, 160, 146, 113, 69, 69,
        168, 188, 81, 155, 131, 49, 58, 202, 192, 236, 217, 49,
    ],
    // atan
    [
        7, 139, 152, 178, 253, 241, 126, 17, 230, 82, 207, 157, 87, 214, 172, 58, 183, 189, 200,
        112, 111, 169, 68, 64, 249, 45, 235, 56, 97, 152, 138, 145,
    ],
    // atan2
    [
        29, 150, 83, 20, 108, 145, 148, 51, 108, 91, 93, 159, 26, 250, 26, 24, 53, 73, 188, 103,
        31, 99, 40, 77, 129, 109, 2, 127, 33, 101, 121, 255,
    ],
    // expf
    [
        185, 72, 219, 15, 141, 242, 20, 240, 143, 212, 215, 141, 57, 175, 23, 117, 186, 109, 95,
        143, 228, 142, 186, 47, 63, 131, 68, 62, 172, 95, 138, 67,
    ],
    // exp2f
    [
        222, 130, 37, 41, 117, 243, 180, 170, 66, 142, 28, 235, 136, 1, 143, 120, 191, 158, 68,
        251, 104, 60, 211, 191, 5, 94, 223, 253, 14, 214, 87, 175,
    ],
    // expm1f
    [
        89, 234, 204, 244, 148, 255, 83, 153, 124, 0, 135, 165, 52, 28, 120, 61, 86, 64, 147, 157,
        15, 116, 92, 157, 220, 155, 236, 2, 117, 148, 145, 242,
    ],
    // logf
    [
        251, 236, 252, 111, 148, 146, 211, 13, 171, 152, 188, 68, 240, 105, 210, 98, 202, 228, 226,
        136, 0, 139, 47, 34, 236, 159, 69, 104, 173, 142, 64, 217,
    ],
    // log2f
    [
        30, 226, 201, 183, 82, 213, 170, 198, 112, 102, 165, 61, 159, 187, 75, 237, 172, 128, 84,
        90, 152, 118, 193, 53, 126, 208, 128, 184, 27, 35, 188, 255,
    ],
    // log10f
    [
        167, 64, 170, 169, 81, 27, 65, 103, 6, 21, 158, 124, 203, 246, 231, 107, 70, 237, 252, 108,
        211, 51, 184, 148, 35, 108, 214, 247, 152, 236, 64, 86,
    ],
    // powf
    [
        171, 117, 110, 30, 54, 60, 203, 232, 62, 229, 114, 194, 39, 0, 58, 158, 220, 178, 211, 153,
        132, 137, 133, 152, 133, 177, 126, 161, 195, 47, 200, 154,
    ],
    // sinf
    [
        197, 201, 95, 148, 97, 123, 229, 233, 146, 72, 214, 223, 69, 254, 88, 165, 186, 216, 28,
        138, 11, 204, 189, 16, 170, 143, 250, 73, 120, 131, 31, 78,
    ],
    // cosf
    [
        180, 191, 116, 160, 85, 86, 134, 195, 206, 168, 30, 147, 145, 172, 204, 144, 247, 237, 107,
        12, 49, 131, 135, 151, 82, 194, 203, 58, 91, 100, 116, 223,
    ],
    // tanf
    [
        42, 176, 130, 220, 6, 47, 30, 192, 231, 122, 254, 86, 215, 177, 147, 147, 180, 243, 146,
        211, 238, 52, 82, 10, 214, 116, 225, 21, 153, 216, 24, 77,
    ],
    // tanhf
    [
        138, 50, 98, 94, 134, 125, 7, 64, 62, 228, 241, 193, 74, 162, 33, 144, 102, 234, 220, 77,
        59, 170, 227, 242, 25, 47, 11, 204, 250, 121, 180, 205,
    ],
    // sqrt
    [
        197, 122, 65, 75, 253, 233, 200, 219, 118, 153, 93, 24, 84, 229, 52, 219, 53, 65, 223, 194,
        171, 233, 20, 23, 102, 33, 216, 6, 117, 79, 144, 95,
    ],
    // sqrtf
    [
        52, 16, 5, 207, 28, 161, 43, 194, 150, 110, 105, 149, 127, 144, 74, 0, 134, 144, 142, 112,
        113, 123, 161, 225, 83, 173, 174, 119, 140, 225, 65, 198,
    ],
    // floor
    [
        1, 150, 166, 160, 174, 142, 186, 113, 55, 172, 164, 176, 61, 118, 8, 202, 154, 65, 62, 227,
        112, 128, 134, 71, 246, 126, 124, 49, 186, 165, 9, 145,
    ],
    // floorf
    [
        39, 131, 94, 36, 46, 11, 237, 173, 87, 143, 204, 8, 226, 22, 13, 45, 116, 89, 23, 26, 146,
        29, 109, 147, 191, 112, 177, 103, 210, 101, 153, 168,
    ],
    // db_to_gain
    [
        20, 235, 161, 181, 74, 143, 204, 60, 118, 66, 232, 99, 58, 28, 56, 66, 71, 33, 245, 89,
        217, 104, 122, 97, 147, 69, 9, 61, 104, 252, 131, 110,
    ],
    // gain_to_db
    [
        53, 154, 191, 33, 85, 242, 31, 206, 232, 63, 130, 114, 249, 27, 9, 31, 49, 120, 40, 247,
        92, 56, 83, 49, 193, 68, 241, 235, 226, 102, 118, 102,
    ],
    // db_to_gain_f32
    [
        78, 136, 254, 239, 79, 11, 125, 217, 140, 57, 211, 176, 53, 177, 103, 196, 79, 229, 121,
        59, 115, 54, 228, 192, 15, 56, 19, 150, 252, 61, 94, 149,
    ],
    // gain_to_db_f32
    [
        172, 50, 25, 62, 163, 1, 115, 54, 255, 174, 92, 170, 209, 210, 242, 251, 192, 135, 115, 26,
        3, 108, 196, 127, 167, 252, 110, 234, 198, 146, 62, 186,
    ],
];
