#!/usr/bin/env bash
# Issue #243 eval 6: codegen drift is structurally impossible.
#
# The SDK's type-shaped surface is a transcription chain with one authority at the top:
#
#   Rust structures and frozen constants
#     -> `miso-engine-parameter-metadata` (offset_of!, registry walk)
#       -> sdk/assets/*.json
#         -> sdk/src/generated/*.ts
#
# Each arrow is re-derived here and compared byte for byte, so a hand edit at *either* checked-in
# layer fails before a consumer can observe the drift. Both halves matter: checking only the
# TypeScript would let a stale JSON asset regenerate stale TypeScript consistently, and checking
# only the JSON would let a hand-edited constant sit in the modules a consumer actually imports.
#
# Red mutation: edit one constant in `sdk/src/generated/abi.ts` -> the second check goes red; edit
# one row in `sdk/assets/miso-engine-v2-abi-layout.json` -> the first does.
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
cd "$repo_root/sdk"

command -v node >/dev/null || { echo "node is required" >&2; exit 2; }
command -v cargo >/dev/null || { echo "cargo is required" >&2; exit 2; }

node codegen/assets.mjs --check
node codegen/generate.mjs --check

# The generated modules must carry their provenance banner: a module without it reads like a file
# a person is invited to edit, which is precisely the invitation this gate exists to withdraw.
for module in src/generated/*.ts; do
  head -1 "$module" | grep -q '@generated by sdk/codegen/generate.mjs' || {
    echo "$module is missing its @generated banner" >&2
    exit 1
  }
done

echo "sdk generated surface is the engine's current output"
