#!/usr/bin/env bash
# Issue #243 eval 6: codegen drift is structurally impossible.
#
# The SDK's type-shaped surface is a transcription chain with one authority at the top:
#
#   Rust structures and frozen constants
#     -> `parameter-metadata` (offset_of!, registry walk)
#       -> sdk/assets/*.json
#         -> sdk/src/generated/*.ts
#
# Each arrow is re-derived here and compared byte for byte, so a hand edit at *either* checked-in
# layer fails before a consumer can observe the drift. Both halves matter: checking only the
# TypeScript would let a stale JSON asset regenerate stale TypeScript consistently, and checking
# only the JSON would let a hand-edited constant sit in the modules a consumer actually imports.
#
# Red mutation: edit one constant in `sdk/src/generated/abi.ts` -> the second check goes red; edit
# one row in `sdk/assets/miso-engine-v1-abi-layout.json` -> the first does.
#
# Usage: check-sdk-generated.sh [ENGINE_ARTIFACT_DIRECTORY]
#
# With no argument the first arrow is re-derived by running the generator (cargo). Issue #1044:
# given the engine artifact directory `build-web-audioworklet.sh` wrote -- the generator's own
# `--write` output at this commit, the documents the SDK package ships -- the JSON assets are
# compared byte for byte with that directory's copies instead, and this gate runs no cargo.
# CI's `sdk` job passes the `artifact` job's download, verified against its closure digest, so a
# Rust change that alters the metadata without refreshing `sdk/assets` fails there.
set -euo pipefail

if (($# > 1)); then
  echo "usage: $0 [ENGINE_ARTIFACT_DIRECTORY]" >&2
  exit 2
fi
repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
artifact_dir=""
if (($# == 1)); then
  [[ -d "$1" && ! -L "$1" ]] || {
    echo "artifact directory must be a non-symlink directory" >&2
    exit 2
  }
  artifact_dir=$(cd "$1" && pwd -P)
fi
cd "$repo_root/sdk"

command -v node >/dev/null || { echo "node is required" >&2; exit 2; }
if [[ -n "$artifact_dir" ]]; then
  node codegen/assets.mjs --check "$artifact_dir"
else
  command -v cargo >/dev/null || { echo "cargo is required" >&2; exit 2; }
  node codegen/assets.mjs --check
fi
node codegen/generate.mjs --check

# The generated modules must carry their provenance banner: a module without it reads like a file
# a person is invited to edit, which is precisely the invitation this gate exists to withdraw.
for module in src/generated/*.ts; do
  head -1 "$module" | grep -q '@generated by sdk/codegen/generate.mjs' || {
    echo "$module is missing its @generated banner" >&2
    exit 1
  }
done

# Issue #243 eval 6: the vendored host declaration is a MIRROR, not a fork.
#
# `sdk/src/browser/shipped-host.d.ts` exists so `tsc --noEmit` can hold the SDK's
# `toWebBootOptions` adapter to the artifact it adapts (see `sdk/test/host-mirror.ts`). A type
# import from the artifact directory could not do that job -- the artifact is a build output that
# does not exist in a source checkout. So the declaration is copied, and the copy is checked here
# rather than trusted: a shipped `.d.ts` that gains, loses or retypes a field and a stale mirror
# that did not follow it is exactly the drift the mirror exists to catch.
if ! cmp -s "$repo_root/hosts/host-web/web/miso-engine-v1-audio-worklet-host.d.ts" \
            "$repo_root/sdk/src/browser/shipped-host.d.ts"; then
  echo "sdk/src/browser/shipped-host.d.ts is not the shipped declaration; refresh it with:" >&2
  echo "  cp hosts/host-web/web/miso-engine-v1-audio-worklet-host.d.ts \\" >&2
  echo "     sdk/src/browser/shipped-host.d.ts" >&2
  diff -u "$repo_root/hosts/host-web/web/miso-engine-v1-audio-worklet-host.d.ts" \
          "$repo_root/sdk/src/browser/shipped-host.d.ts" >&2 || true
  exit 1
fi

echo "sdk generated surface is the engine's current output"
