#!/usr/bin/env bash
# Mutation tests proving that the workspace-policy guard rejects each protected failure class.
set -euo pipefail

script_directory="$(cd "$(dirname "$0")" && pwd)"
policy_script="$script_directory/check-workspace-policy.sh"
scratch_root="$(mktemp -d)"
trap 'rm -rf -- "$scratch_root"' EXIT

create_valid_fixture() {
    local fixture_root="$1"
    mkdir -p \
        "$fixture_root/crates/library/src" \
        "$fixture_root/crates/math" \
        "$fixture_root/fuzz" \
        "$fixture_root/hosts/binary/src" \
        "$fixture_root/tools" \
        "$fixture_root/sidecars"

    cp "$script_directory/../LICENSE" "$fixture_root/LICENSE"
    printf '%s\n' 'Miso Engine' >"$fixture_root/NOTICE"
    printf '%s\n' 'See crates/math/LICENSE-libm.txt.' >"$fixture_root/THIRD_PARTY_LICENSES.md"
    printf '%s\n' 'fixture third-party license' >"$fixture_root/crates/math/LICENSE-libm.txt"
    printf '%s\n' \
        '[workspace.package]' \
        'license = "Apache-2.0"' \
        >"$fixture_root/Cargo.toml"
    printf '%s\n' \
        '[package]' \
        'name = "session-fuzz"' \
        'license = "Apache-2.0"' \
        >"$fixture_root/fuzz/Cargo.toml"
    # A minimal, cargo-free lockfile so the retired-delivery-codec lockfile scan has a fixed
    # target; its exact contents do not matter, only that it exists and names no retired crate.
    printf '%s\n' \
        '# This file is automatically @generated by Cargo.' \
        '# It is not intended for manual editing.' \
        'version = 4' \
        >"$fixture_root/Cargo.lock"

    printf '%s\n' \
        '[package]' \
        'name = "library"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "library"' \
        '' \
        '[features]' \
        'default = []' \
        >"$fixture_root/crates/library/Cargo.toml"
    printf '//! fixture\n' >"$fixture_root/crates/library/src/lib.rs"

    printf '%s\n' \
        '[package]' \
        'name = "binary"' \
        'license.workspace = true' \
        '' \
        '[[bin]]' \
        'name = "binary"' \
        'path = "src/main.rs"' \
        '' \
        '[features]' \
        'default = []' \
        >"$fixture_root/hosts/binary/Cargo.toml"
    printf 'fn main() {}\n' >"$fixture_root/hosts/binary/src/main.rs"
}

expect_failure() {
    local fixture_name="$1"
    local fixture_root="$scratch_root/$fixture_name"
    shift
    create_valid_fixture "$fixture_root"
    "$@" "$fixture_root"

    if bash "$policy_script" "$fixture_root" >/dev/null 2>&1; then
        printf 'policy mutation unexpectedly passed: %s\n' "$fixture_name" >&2
        exit 1
    fi
}

# The miso-engine- prefix convention was retired by the prefix-strip rename
# (docs/rulings/prefix-strip-inventory.md). A package that reintroduces it must still fail --
# this is the regression the gate exists to catch now that the prefix is no longer required.
mutate_package_prefix() {
    local root="$1"
    # `0,/pat/{s/pat/x/}` limits the substitution to the first match in the file (the
    # [package] name line), so it does not also clobber the [lib] name line below it, which
    # is textually identical for a single-word crate name.
    sed -i '0,/name = "library"/{s/name = "library"/name = "miso-engine-library"/}' \
        "$root/crates/library/Cargo.toml"
}

# Same regression, spelled with the underscore form, which the check also forbids explicitly
# (a partially-reverted rename could leave the package name underscored instead of hyphenated).
mutate_package_prefix_underscore_form() {
    local root="$1"
    sed -i '0,/name = "library"/{s/name = "library"/name = "miso_engine_library"/}' \
        "$root/crates/library/Cargo.toml"
}

# The directory basename must equal the package name exactly now that there is no prefix left to
# distinguish "close enough" from correct.
mutate_directory_mismatch() {
    local root="$1"
    sed -i '0,/name = "library"/{s/name = "library"/name = "elsewhere"/}' \
        "$root/crates/library/Cargo.toml"
}

mutate_lib_identifier() {
    local root="$1"
    # Scoped to the [lib] section onward so this does not also clobber the [package] name
    # line above it, which is textually identical for a single-word crate name.
    sed -i '/^\[lib\]$/,$ s/name = "library"/name = "wrong"/' \
        "$root/crates/library/Cargo.toml"
}

mutate_bin_identifier() {
    local root="$1"
    sed -i '/^\[\[bin\]\]$/,$ s/name = "binary"/name = "wrong"/' \
        "$root/hosts/binary/Cargo.toml"
}

allow_secondary_tool_bin() {
    local root="$1"
    create_valid_fixture "$root"
    sed -i '/^\[\[bin\]\]$/,$ s/name = "binary"/name = "binary_probe"/' \
        "$root/hosts/binary/Cargo.toml"
    bash "$policy_script" "$root" >/dev/null
}

mutate_hardware_feature() {
    local root="$1"
    printf 'avx2 = []\n' >>"$root/crates/library/Cargo.toml"
}

mutate_track_limit() {
    local root="$1"
    printf 'const MAX_TRACKS: usize = 64;\n' \
        >>"$root/crates/library/src/lib.rs"
}

mutate_prelaunch_abi_generation() {
    local root="$1"
    printf '%s%s%s\n' 'pub const MISO_ENGINE_' 'V' '2_ABI_VERSION: u32 = 2;' \
        >>"$root/crates/library/src/lib.rs"
}

mutate_prelaunch_product_generation() {
    local root="$1"
    printf '%s%s%s\n' '//! Engine ' 'V' '2 public surface' \
        >>"$root/crates/library/src/lib.rs"
}

mutate_versioned_worklet_implementation() {
    local root="$1"
    printf '%s%s%s\n' 'class MisoEngine' 'V2' 'AudioWorkletProcessor {}' \
        >>"$root/hosts/binary/src/worklet.js"
}

mutate_global_isa() {
    local root="$1"
    mkdir -p "$root/.cargo"
    printf '%s\n' '[build]' 'rustflags = ["-C", "target-cpu=native"]' \
        >"$root/.cargo/config.toml"
}

mutate_unscoped_isa_pin() {
    local root="$1"
    mkdir -p "$root/.cargo"
    printf '%s\n' '[build]' 'rustflags = ["-C", "target-feature=+avx2,+fma"]' \
        >"$root/.cargo/config.toml"
}

mutate_extra_isa_feature() {
    local root="$1"
    mkdir -p "$root/.cargo"
    printf '%s\n' "[target.'cfg(target_arch = \"x86_64\")']" \
        'rustflags = ["-C", "target-feature=+avx2,+fma,+avx512f"]' \
        >"$root/.cargo/config.toml"
}

allow_approved_isa_pin() {
    local root="$1"
    create_valid_fixture "$root"
    mkdir -p "$root/.cargo"
    printf '%s\n' \
        '# Master plan #83 D4: the approved x86-64-v3 pin, with target-feature in a comment.' \
        "[target.'cfg(target_arch = \"x86_64\")']" \
        'rustflags = ["-C", "target-feature=+avx2,+fma"]' \
        >"$root/.cargo/config.toml"
    bash "$policy_script" "$root" >/dev/null
}

# sidecars/<name> is no longer special-cased: it is subject to exactly the same bare-name,
# directory-equals-package-name and sysroot-collision rules as crates/hosts/tools.
allow_sidecar_valid() {
    local root="$1"
    create_valid_fixture "$root"
    mkdir -p "$root/sidecars/example/src"
    printf '%s\n' \
        '[package]' \
        'name = "example"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "example"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/sidecars/example/Cargo.toml"
    printf '//! fixture\n' >"$root/sidecars/example/src/lib.rs"
    bash "$policy_script" "$root" >/dev/null
}

mutate_sidecar_package_prefix() {
    local root="$1"
    mkdir -p "$root/sidecars/example/src"
    printf '%s\n' \
        '[package]' \
        'name = "miso-engine-example"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "miso_engine_example"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/sidecars/example/Cargo.toml"
    printf '//! fixture\n' >"$root/sidecars/example/src/lib.rs"
}

# The directory-equals-package-name rule applies regardless of nesting depth: a manifest two
# directories under sidecars/ whose package name does not match its own directory basename must
# still fail, exactly as it would under crates/hosts/tools.
mutate_sidecar_nested_directory_mismatch() {
    local root="$1"
    mkdir -p "$root/sidecars/vendor/anything/src"
    printf '%s\n' \
        '[package]' \
        'name = "vendored-thing"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "vendored_thing"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/sidecars/vendor/anything/Cargo.toml"
    printf '//! fixture\n' >"$root/sidecars/vendor/anything/src/lib.rs"
}

# `core`, and the rest of the Rust sysroot/prelude names, must never be a package name: `core`
# silently shadows the sysroot `core` crate for every dependent (docs/rulings/prefix-strip-inventory.md).
mutate_sysroot_collision() {
    local root="$1"
    mkdir -p "$root/crates/core/src"
    printf '%s\n' \
        '[package]' \
        'name = "core"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "core"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/crates/core/Cargo.toml"
    printf '//! fixture\n' >"$root/crates/core/src/lib.rs"
}

# Issue #356/#359: the delivery-codec boundary folded from check-delivery-codec-boundary.py.
mutate_retired_manifest_package_name() {
    local root="$1"
    mkdir -p "$root/sidecars/flac-decoder/src"
    printf '%s\n' \
        '[package]' \
        'name = "flac-decoder"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "flac_decoder"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/sidecars/flac-decoder/Cargo.toml"
    printf '//! fixture\n' >"$root/sidecars/flac-decoder/src/lib.rs"
}

mutate_retired_stub_directory() {
    local root="$1"
    # No Cargo.toml: a bare leftover directory, invisible to the manifest loop.
    mkdir -p "$root/tools/stem-publisher"
}

mutate_retired_manifest_dependency() {
    local root="$1"
    printf '\n[dependencies]\nflacenc = "0.5.1"\n' >>"$root/crates/library/Cargo.toml"
}

mutate_retired_manifest_dependency_rename() {
    local root="$1"
    printf '\n[dependencies]\ndelivery = { package = "symphonia", version = "0.5.4" }\n' \
        >>"$root/crates/library/Cargo.toml"
}

mutate_retired_lockfile_identity() {
    local root="$1"
    printf '\n[[package]]\nname = "symphonia"\nversion = "0.5.4"\n' >>"$root/Cargo.lock"
}

mutate_prelude_collision() {
    local root="$1"
    mkdir -p "$root/crates/std/src"
    printf '%s\n' \
        '[package]' \
        'name = "std"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "std"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/crates/std/Cargo.toml"
    printf '//! fixture\n' >"$root/crates/std/src/lib.rs"
}

valid_root="$scratch_root/valid_root"
create_valid_fixture "$valid_root"
bash "$policy_script" "$valid_root" >/dev/null

# #104 phase D: a cargo target-dir spill at the workspace root.
mutate_root_target_spill() {
    local root="$1"
    mkdir -p "$root/release/.fingerprint"
    printf '{}\n' >"$root/release/.fingerprint/lib-example.json"
}

mutate_root_rustc_info() {
    local root="$1"
    printf '{}\n' >"$root/.rustc_info.json"
}

mutate_root_cachedir_tag() {
    local root="$1"
    printf 'Signature: 8a477f597d28d172789f06886806bc55\n' >"$root/CACHEDIR.TAG"
}

expect_failure package-prefix mutate_package_prefix
expect_failure package-prefix-underscore-form mutate_package_prefix_underscore_form
expect_failure directory-mismatch mutate_directory_mismatch
expect_failure lib-identifier mutate_lib_identifier
expect_failure bin-identifier mutate_bin_identifier
expect_failure hardware-feature mutate_hardware_feature
expect_failure track-limit mutate_track_limit
expect_failure prelaunch-abi-generation mutate_prelaunch_abi_generation
expect_failure prelaunch-product-generation mutate_prelaunch_product_generation
expect_failure versioned-worklet-implementation mutate_versioned_worklet_implementation
expect_failure global-isa mutate_global_isa
expect_failure unscoped-isa-pin mutate_unscoped_isa_pin
expect_failure extra-isa-feature mutate_extra_isa_feature
expect_failure root-target-spill mutate_root_target_spill
expect_failure root-rustc-info mutate_root_rustc_info
expect_failure root-cachedir-tag mutate_root_cachedir_tag
expect_failure sidecar-package-prefix mutate_sidecar_package_prefix
expect_failure sidecar-nested-directory-mismatch mutate_sidecar_nested_directory_mismatch
expect_failure sysroot-collision mutate_sysroot_collision
expect_failure prelude-collision mutate_prelude_collision
expect_failure retired-manifest-package-name mutate_retired_manifest_package_name
expect_failure retired-stub-directory mutate_retired_stub_directory
expect_failure retired-manifest-dependency mutate_retired_manifest_dependency
expect_failure retired-manifest-dependency-rename mutate_retired_manifest_dependency_rename
expect_failure retired-lockfile-identity mutate_retired_lockfile_identity

mutate_missing_license() {
    local root="$1"
    rm -- "$root/LICENSE"
}

mutate_workspace_license() {
    local root="$1"
    sed -i 's/license = "Apache-2.0"/license = "MIT"/' "$root/Cargo.toml"
}

mutate_package_license_inheritance() {
    local root="$1"
    sed -i '/license\.workspace = true/d' "$root/crates/library/Cargo.toml"
}

mutate_npm_license() {
    local root="$1"
    mkdir -p "$root/sdk"
    printf '%s\n' '{"name":"fixture","license":"MIT"}' >"$root/sdk/package.json"
}

expect_failure missing-license mutate_missing_license
expect_failure workspace-license mutate_workspace_license
expect_failure package-license-inheritance mutate_package_license_inheritance
expect_failure npm-license mutate_npm_license

# `rg` exits 2 (not 1) when a search root does not exist, and `if rg ...; then fail; fi` reads
# both 1 and 2 as "no violation". A fixture whose sidecars/ directory is removed after creation
# must still fail loudly (naming the missing root), not pass as if the scan had run clean.
mutate_missing_sidecars_root() {
    local root="$1"
    rm -rf -- "$root/sidecars"
}

expect_failure missing-sidecars-root mutate_missing_sidecars_root
allow_secondary_tool_bin "$scratch_root/secondary-tool-bin"
allow_approved_isa_pin "$scratch_root/approved-isa-pin"
allow_sidecar_valid "$scratch_root/sidecar-valid"

printf 'workspace policy mutation tests: ok\n'
