#!/usr/bin/env bash
# Mutation tests proving that the workspace-policy guard rejects each protected failure class.
set -euo pipefail

script_directory="$(cd "$(dirname "$0")" && pwd)"
policy_script="$script_directory/check-workspace-policy.sh"
scratch_root="$(mktemp -d)"
trap 'rm -rf -- "$scratch_root"' EXIT

create_valid_fixture() {
    local fixture_root="$1"
    mkdir -p \
        "$fixture_root/crates/library/src" \
        "$fixture_root/crates/math" \
        "$fixture_root/fuzz" \
        "$fixture_root/hosts/binary/src" \
        "$fixture_root/tools" \
        "$fixture_root/sidecars"

    cp "$script_directory/../LICENSE" "$fixture_root/LICENSE"
    printf '%s\n' 'Miso Engine' >"$fixture_root/NOTICE"
    printf '%s\n' 'See crates/math/LICENSE-libm.txt.' >"$fixture_root/THIRD_PARTY_LICENSES.md"
    printf '%s\n' 'fixture third-party license' >"$fixture_root/crates/math/LICENSE-libm.txt"
    printf '%s\n' \
        '[workspace.package]' \
        'license = "Apache-2.0"' \
        >"$fixture_root/Cargo.toml"
    printf '%s\n' \
        '[package]' \
        'name = "session-fuzz"' \
        'license = "Apache-2.0"' \
        >"$fixture_root/fuzz/Cargo.toml"
    # A minimal, cargo-free lockfile so the retired-delivery-codec lockfile scan has a fixed
    # target; its exact contents do not matter, only that it exists and names no retired crate.
    printf '%s\n' \
        '# This file is automatically @generated by Cargo.' \
        '# It is not intended for manual editing.' \
        'version = 4' \
        >"$fixture_root/Cargo.lock"

    printf '%s\n' \
        '[package]' \
        'name = "library"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "library"' \
        '' \
        '[features]' \
        'default = []' \
        >"$fixture_root/crates/library/Cargo.toml"
    printf '//! fixture\n' >"$fixture_root/crates/library/src/lib.rs"

    printf '%s\n' \
        '[package]' \
        'name = "binary"' \
        'license.workspace = true' \
        '' \
        '[[bin]]' \
        'name = "binary"' \
        'path = "src/main.rs"' \
        '' \
        '[features]' \
        'default = []' \
        >"$fixture_root/hosts/binary/Cargo.toml"
    printf 'fn main() {}\n' >"$fixture_root/hosts/binary/src/main.rs"
}

expect_failure() {
    local fixture_name="$1"
    local fixture_root="$scratch_root/$fixture_name"
    shift
    create_valid_fixture "$fixture_root"
    "$@" "$fixture_root"

    if bash "$policy_script" "$fixture_root" >/dev/null 2>&1; then
        printf 'policy mutation unexpectedly passed: %s\n' "$fixture_name" >&2
        exit 1
    fi
}

# N20: like expect_failure, but also asserts the failure message contains the given substring --
# proving the mutation was caught by the rule it targets, not by some unrelated failure that
# happens to also reject the fixture.
expect_failure_with_message() {
    local fixture_name="$1" expected_substring="$2"
    local fixture_root="$scratch_root/$fixture_name"
    shift 2
    create_valid_fixture "$fixture_root"
    "$@" "$fixture_root"

    local output
    if output="$(bash "$policy_script" "$fixture_root" 2>&1)"; then
        printf 'policy mutation unexpectedly passed: %s\n' "$fixture_name" >&2
        exit 1
    fi
    if [[ "$output" != *"$expected_substring"* ]]; then
        printf 'policy mutation %s failed for the wrong reason (expected to contain %q): %s\n' \
            "$fixture_name" "$expected_substring" "$output" >&2
        exit 1
    fi
}

# The miso-engine- prefix convention was retired by the prefix-strip rename
# (docs/rulings/prefix-strip-inventory.md). A package that reintroduces it must still fail --
# this is the regression the gate exists to catch now that the prefix is no longer required.
mutate_package_prefix() {
    local root="$1"
    # `0,/pat/{s/pat/x/}` limits the substitution to the first match in the file (the
    # [package] name line), so it does not also clobber the [lib] name line below it, which
    # is textually identical for a single-word crate name.
    sed -i '0,/name = "library"/{s/name = "library"/name = "miso-engine-library"/}' \
        "$root/crates/library/Cargo.toml"
}

# Same regression, spelled with the underscore form, which the check also forbids explicitly
# (a partially-reverted rename could leave the package name underscored instead of hyphenated).
mutate_package_prefix_underscore_form() {
    local root="$1"
    sed -i '0,/name = "library"/{s/name = "library"/name = "miso_engine_library"/}' \
        "$root/crates/library/Cargo.toml"
}

# The directory basename must equal the package name exactly now that there is no prefix left to
# distinguish "close enough" from correct.
mutate_directory_mismatch() {
    local root="$1"
    sed -i '0,/name = "library"/{s/name = "library"/name = "elsewhere"/}' \
        "$root/crates/library/Cargo.toml"
}

mutate_lib_identifier() {
    local root="$1"
    # Scoped to the [lib] section onward so this does not also clobber the [package] name
    # line above it, which is textually identical for a single-word crate name.
    sed -i '/^\[lib\]$/,$ s/name = "library"/name = "wrong"/' \
        "$root/crates/library/Cargo.toml"
}

mutate_bin_identifier() {
    local root="$1"
    sed -i '/^\[\[bin\]\]$/,$ s/name = "binary"/name = "wrong"/' \
        "$root/hosts/binary/Cargo.toml"
}

allow_secondary_tool_bin() {
    local root="$1"
    create_valid_fixture "$root"
    sed -i '/^\[\[bin\]\]$/,$ s/name = "binary"/name = "binary_probe"/' \
        "$root/hosts/binary/Cargo.toml"
    bash "$policy_script" "$root" >/dev/null
}

mutate_hardware_feature() {
    local root="$1"
    printf 'avx2 = []\n' >>"$root/crates/library/Cargo.toml"
}

mutate_track_limit() {
    local root="$1"
    printf 'const MAX_TRACKS: usize = 64;\n' \
        >>"$root/crates/library/src/lib.rs"
}

mutate_prelaunch_abi_generation() {
    local root="$1"
    printf '%s%s%s\n' 'pub const MISO_ENGINE_' 'V' '2_ABI_VERSION: u32 = 2;' \
        >>"$root/crates/library/src/lib.rs"
}

mutate_prelaunch_product_generation() {
    local root="$1"
    printf '%s%s%s\n' '//! Engine ' 'V' '2 public surface' \
        >>"$root/crates/library/src/lib.rs"
}

mutate_versioned_worklet_implementation() {
    local root="$1"
    printf '%s%s%s\n' 'class MisoEngine' 'V2' 'AudioWorkletProcessor {}' \
        >>"$root/hosts/binary/src/worklet.js"
}

mutate_global_isa() {
    local root="$1"
    mkdir -p "$root/.cargo"
    printf '%s\n' '[build]' 'rustflags = ["-C", "target-cpu=native"]' \
        >"$root/.cargo/config.toml"
}

mutate_unscoped_isa_pin() {
    local root="$1"
    mkdir -p "$root/.cargo"
    printf '%s\n' '[build]' 'rustflags = ["-C", "target-feature=+avx2,+fma"]' \
        >"$root/.cargo/config.toml"
}

mutate_extra_isa_feature() {
    local root="$1"
    mkdir -p "$root/.cargo"
    printf '%s\n' "[target.'cfg(target_arch = \"x86_64\")']" \
        'rustflags = ["-C", "target-feature=+avx2,+fma,+avx512f"]' \
        >"$root/.cargo/config.toml"
}

allow_approved_isa_pin() {
    local root="$1"
    create_valid_fixture "$root"
    mkdir -p "$root/.cargo"
    printf '%s\n' \
        '# Master plan #83 D4: the approved x86-64-v3 pin, with target-feature in a comment.' \
        "[target.'cfg(target_arch = \"x86_64\")']" \
        'rustflags = ["-C", "target-feature=+avx2,+fma"]' \
        >"$root/.cargo/config.toml"
    bash "$policy_script" "$root" >/dev/null
}

# sidecars/<name> is no longer special-cased: it is subject to exactly the same bare-name,
# directory-equals-package-name and sysroot-collision rules as crates/hosts/tools.
allow_sidecar_valid() {
    local root="$1"
    create_valid_fixture "$root"
    mkdir -p "$root/sidecars/example/src"
    printf '%s\n' \
        '[package]' \
        'name = "example"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "example"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/sidecars/example/Cargo.toml"
    printf '//! fixture\n' >"$root/sidecars/example/src/lib.rs"
    bash "$policy_script" "$root" >/dev/null
}

mutate_sidecar_package_prefix() {
    local root="$1"
    mkdir -p "$root/sidecars/example/src"
    printf '%s\n' \
        '[package]' \
        'name = "miso-engine-example"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "miso_engine_example"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/sidecars/example/Cargo.toml"
    printf '//! fixture\n' >"$root/sidecars/example/src/lib.rs"
}

# The directory-equals-package-name rule applies regardless of nesting depth: a manifest two
# directories under sidecars/ whose package name does not match its own directory basename must
# still fail, exactly as it would under crates/hosts/tools.
mutate_sidecar_nested_directory_mismatch() {
    local root="$1"
    mkdir -p "$root/sidecars/vendor/anything/src"
    printf '%s\n' \
        '[package]' \
        'name = "vendored-thing"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "vendored_thing"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/sidecars/vendor/anything/Cargo.toml"
    printf '//! fixture\n' >"$root/sidecars/vendor/anything/src/lib.rs"
}

# `core`, and the rest of the Rust sysroot/prelude names, must never be a package name: `core`
# silently shadows the sysroot `core` crate for every dependent (docs/rulings/prefix-strip-inventory.md).
mutate_sysroot_collision() {
    local root="$1"
    mkdir -p "$root/crates/core/src"
    printf '%s\n' \
        '[package]' \
        'name = "core"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "core"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/crates/core/Cargo.toml"
    printf '//! fixture\n' >"$root/crates/core/src/lib.rs"
}

# Issue #356/#359: the delivery-codec boundary folded from check-delivery-codec-boundary.py.
mutate_retired_manifest_package_name() {
    local root="$1"
    mkdir -p "$root/sidecars/flac-decoder/src"
    printf '%s\n' \
        '[package]' \
        'name = "flac-decoder"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "flac_decoder"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/sidecars/flac-decoder/Cargo.toml"
    printf '//! fixture\n' >"$root/sidecars/flac-decoder/src/lib.rs"
}

mutate_retired_stub_directory() {
    local root="$1"
    # No Cargo.toml: a bare leftover directory, invisible to the manifest loop.
    mkdir -p "$root/tools/stem-publisher"
}

mutate_retired_manifest_dependency() {
    local root="$1"
    printf '\n[dependencies]\nflacenc = "0.5.1"\n' >>"$root/crates/library/Cargo.toml"
}

mutate_retired_manifest_dependency_rename() {
    local root="$1"
    printf '\n[dependencies]\ndelivery = { package = "symphonia", version = "0.5.4" }\n' \
        >>"$root/crates/library/Cargo.toml"
}

mutate_retired_lockfile_identity() {
    local root="$1"
    printf '\n[[package]]\nname = "symphonia"\nversion = "0.5.4"\n' >>"$root/Cargo.lock"
}

# S8: the forbidden-name scan must reach every Cargo.toml in the tree, not just the six
# hard-coded roots the prior scan_forbidden call used -- a nested manifest under sdk/ (outside
# crates/hosts/tools/sidecars/fuzz) must still fail.
mutate_nested_manifest_dependency() {
    local root="$1"
    mkdir -p "$root/sdk/native"
    printf '%s\n' \
        '[package]' \
        'name = "x"' \
        '' \
        '[dependencies]' \
        'symphonia = "0.5.4"' \
        >"$root/sdk/native/Cargo.toml"
}

# N16: the bare-stub directory scan must reach any depth under any root, not `-maxdepth 2` under
# four hard-coded roots -- a retired name three levels under tools/ must still fail.
mutate_deep_retired_stub_directory() {
    local root="$1"
    mkdir -p "$root/tools/a/b/flac-decoder"
}

# N17: a retired name's mere mention inside a '#' comment must NOT trip the gate -- only a real
# dependency/rename/package entry should.
allow_retired_name_in_comment() {
    local root="$1"
    create_valid_fixture "$root"
    printf '\n# we deliberately do not depend on symphonia\n' >>"$root/crates/library/Cargo.toml"
    bash "$policy_script" "$root" >/dev/null
}

mutate_prelude_collision() {
    local root="$1"
    mkdir -p "$root/crates/std/src"
    printf '%s\n' \
        '[package]' \
        'name = "std"' \
        'license.workspace = true' \
        '' \
        '[lib]' \
        'name = "std"' \
        '' \
        '[features]' \
        'default = []' \
        >"$root/crates/std/Cargo.toml"
    printf '//! fixture\n' >"$root/crates/std/src/lib.rs"
}

valid_root="$scratch_root/valid_root"
create_valid_fixture "$valid_root"
bash "$policy_script" "$valid_root" >/dev/null

# #104 phase D: a cargo target-dir spill at the workspace root.
mutate_root_target_spill() {
    local root="$1"
    mkdir -p "$root/release/.fingerprint"
    printf '{}\n' >"$root/release/.fingerprint/lib-example.json"
}

mutate_root_rustc_info() {
    local root="$1"
    printf '{}\n' >"$root/.rustc_info.json"
}

mutate_root_cachedir_tag() {
    local root="$1"
    printf 'Signature: 8a477f597d28d172789f06886806bc55\n' >"$root/CACHEDIR.TAG"
}

expect_failure package-prefix mutate_package_prefix
expect_failure package-prefix-underscore-form mutate_package_prefix_underscore_form
expect_failure directory-mismatch mutate_directory_mismatch
expect_failure lib-identifier mutate_lib_identifier
expect_failure bin-identifier mutate_bin_identifier
expect_failure hardware-feature mutate_hardware_feature
expect_failure track-limit mutate_track_limit
expect_failure prelaunch-abi-generation mutate_prelaunch_abi_generation
expect_failure prelaunch-product-generation mutate_prelaunch_product_generation
expect_failure versioned-worklet-implementation mutate_versioned_worklet_implementation
expect_failure global-isa mutate_global_isa
expect_failure unscoped-isa-pin mutate_unscoped_isa_pin
expect_failure extra-isa-feature mutate_extra_isa_feature
expect_failure root-target-spill mutate_root_target_spill
expect_failure root-rustc-info mutate_root_rustc_info
expect_failure root-cachedir-tag mutate_root_cachedir_tag
expect_failure sidecar-package-prefix mutate_sidecar_package_prefix
expect_failure sidecar-nested-directory-mismatch mutate_sidecar_nested_directory_mismatch
expect_failure sysroot-collision mutate_sysroot_collision
expect_failure prelude-collision mutate_prelude_collision
expect_failure retired-manifest-package-name mutate_retired_manifest_package_name
expect_failure retired-stub-directory mutate_retired_stub_directory
expect_failure retired-manifest-dependency mutate_retired_manifest_dependency
expect_failure retired-manifest-dependency-rename mutate_retired_manifest_dependency_rename
expect_failure retired-lockfile-identity mutate_retired_lockfile_identity
expect_failure_with_message nested-manifest-dependency \
    'retired delivery-codec Cargo identity is forbidden' mutate_nested_manifest_dependency
expect_failure_with_message deep-retired-stub-directory \
    'retired delivery-codec directory remains' mutate_deep_retired_stub_directory

mutate_missing_license() {
    local root="$1"
    rm -- "$root/LICENSE"
}

mutate_workspace_license() {
    local root="$1"
    sed -i 's/license = "Apache-2.0"/license = "MIT"/' "$root/Cargo.toml"
}

mutate_package_license_inheritance() {
    local root="$1"
    sed -i '/license\.workspace = true/d' "$root/crates/library/Cargo.toml"
}

mutate_npm_license() {
    local root="$1"
    mkdir -p "$root/sdk"
    printf '%s\n' '{"name":"fixture","license":"MIT"}' >"$root/sdk/package.json"
}

expect_failure missing-license mutate_missing_license
expect_failure workspace-license mutate_workspace_license
expect_failure package-license-inheritance mutate_package_license_inheritance
expect_failure npm-license mutate_npm_license

# `rg` exits 2 (not 1) when a search root does not exist, and `if rg ...; then fail; fi` reads
# both 1 and 2 as "no violation". A fixture whose sidecars/ directory is removed after creation
# must still fail loudly (naming the missing root), not pass as if the scan had run clean.
mutate_missing_sidecars_root() {
    local root="$1"
    rm -rf -- "$root/sidecars"
}

expect_failure missing-sidecars-root mutate_missing_sidecars_root
allow_secondary_tool_bin "$scratch_root/secondary-tool-bin"
allow_approved_isa_pin "$scratch_root/approved-isa-pin"
allow_sidecar_valid "$scratch_root/sidecar-valid"
allow_retired_name_in_comment "$scratch_root/retired-name-comment"

# Issue #404's finite producer table. Each row names one external stage and injects exit 73 after
# either no output or the real tool's complete, policy-valid output. Unselected calls always run
# the saved real executable. The checker must report the selected operation, status and sentinel;
# an unrelated rejection cannot satisfy the assertion.
make_fault_shim() {
    local shim="$1" tool="$2" match="$3" occurrence="$4" mode="$5" label="$6"
    local real_tool
    real_tool="$(command -v "$tool")"
    mkdir -p "$shim"
    printf '%s\n' \
        '#!/usr/bin/env bash' \
        'set -u' \
        "real_tool='$real_tool'" \
        "match='$match'" \
        "occurrence='$occurrence'" \
        "mode='$mode'" \
        "label='$label'" \
        'state=${WORKSPACE_FAULT_STATE:?}' \
        'args="$*"' \
        'if [[ "$args" == *"$match"* ]]; then' \
        '  count=0; [[ ! -f "$state" ]] || count=$(<"$state")' \
        '  count=$((count + 1)); printf "%s\n" "$count" >"$state"' \
        '  if (( count == occurrence )); then' \
        '    [[ "$mode" != complete ]] || "$real_tool" "$@"' \
        '    printf "WORKSPACE_FAULT:%s:status=73\n" "$label" >&2' \
        '    exit 73' \
        '  fi' \
        'fi' \
        'exec "$real_tool" "$@"' \
        >"$shim/$tool"
    chmod +x "$shim/$tool"
}

assert_fault_rejected() {
    local name="$1" tool="$2" match="$3" occurrence="$4" mode="$5" expected="$6"
    local root="$scratch_root/fault-$name" shim="$scratch_root/shim-$name" output rc
    create_valid_fixture "$root"
    [[ "$name" != isa-* ]] || {
        mkdir -p "$root/.cargo"
        printf '%s\n' "[target.'cfg(target_arch = \"x86_64\")']" \
            'rustflags = ["-C", "target-feature=+avx2,+fma"]' >"$root/.cargo/config.toml"
    }
    [[ "$name" != npm-* ]] || {
        mkdir -p "$root/sdk"
        printf '%s\n' '{"name":"fixture","license":"Apache-2.0"}' >"$root/sdk/package.json"
        printf '%s\n' '{"packages":{"":{"license":"Apache-2.0"}}}' >"$root/sdk/package-lock.json"
    }
    [[ "$name" != git-list ]] || { git -C "$root" init -q; git -C "$root" add .; }
    make_fault_shim "$shim" "$tool" "$match" "$occurrence" "$mode" "$name"
    output="$(WORKSPACE_FAULT_STATE="$shim/state" PATH="$shim:$PATH" \
        bash "$policy_script" "$root" 2>&1)" && rc=0 || rc=$?
    if (( rc == 0 )); then
        printf 'directed fault unexpectedly passed: %s\n' "$name" >&2
        return 97
    fi
    [[ "$output" == *"$expected"* && "$output" == *"status 73"* && \
       "$output" == *"WORKSPACE_FAULT:$name:status=73"* ]] || {
        printf 'directed fault %s had wrong payload/status: %s\n' "$name" "$output" >&2
        exit 96
    }
}

# Population discovery and sorting: npm manifests, npm locks, collective Cargo manifests,
# retired directory stubs and shallow fingerprints. Empty/error is used for intrinsically empty
# valid populations; complete/error proves a valid prefix cannot override producer failure.
fault_cases=(
 'npm-find-empty|find|-name package.json|1|empty|find npm-manifests failed'
 'npm-find-complete|find|-name package.json|1|complete|find npm-manifests failed'
 'npm-sort|sort|npm-manifests.out|1|complete|sort npm manifests failed'
 'npm-lock-find|find|-name package-lock.json|1|complete|find npm-locks failed'
 'npm-lock-sort|sort|npm-locks.out|1|complete|sort npm locks failed'
 'cargo-find-empty|find|crates hosts tools sidecars|1|empty|find cargo-manifests failed'
 'cargo-find-complete|find|crates hosts tools sidecars|1|complete|find cargo-manifests failed'
 'cargo-sort|sort|cargo-manifests.out|1|complete|sort Cargo manifests failed'
 'retired-find|find|-name flac-decoder|1|empty|retired-directory discovery failed'
 'fingerprint-find|find|-mindepth 2 -maxdepth 2|1|empty|fingerprint discovery failed'
 'sha-producer|sha256sum|LICENSE|1|complete|sha256sum LICENSE failed'
 'sha-extractor|awk|license_sha256.out|1|complete|LICENSE digest extraction failed'
 'npm-jq|jq|.license ==|1|complete|jq ./sdk/package.json failed'
 'npm-lock-jq|jq|.packages[""].license|1|complete|jq ./sdk/package-lock.json failed'
 'workspace-search|rg|license = "Apache-2.0" Cargo.toml|1|complete|rg workspace-license failed'
 'fuzz-search|rg|license = "Apache-2.0" fuzz/Cargo.toml|1|complete|rg fuzz-license failed'
 'inventory-search|rg|LICENSE-libm|1|complete|rg libm-inventory failed'
 'package-search-late|rg|hosts/binary/Cargo.toml|1|complete|rg package-license-'
 'package-extract-late|awk|-v section=package|2|complete|package name extraction hosts/binary/Cargo.toml failed'
 'lib-extract|awk|-v section=lib|1|empty|lib name extraction crates/library/Cargo.toml failed'
 'bin-extract|awk|-v section=bin|2|complete|bin name extraction hosts/binary/Cargo.toml failed'
 'git-classify|git|rev-parse --is-inside-work-tree|1|empty|git repository classification failed'
 'git-list|git|ls-files -z|1|complete|git tracked-path listing failed'
 'fallback-list|find|-type f -not -path ./.git/*|1|complete|fallback tracked-path find failed'
 'nul-convert|tr|\0|1|complete|tracked-path NUL conversion failed'
 'path-normalize|sed|nul-to-lines.out|1|complete|tracked-path normalization failed'
 'manifest-filter|awk|-F/|1|complete|tracked Cargo manifest filter failed'
 'manifest-sort|sort|cargo-path-filter.out|1|complete|tracked Cargo manifest sort failed'
 'comment-strip|awk|in_string=0; out=|2|complete|comment stripping crates/library/Cargo.toml failed'
 'retired-scan|rg|strip-comments.out|1|complete|retired identity scan Cargo.toml failed'
 'isa-source|rg|target-cpu|1|complete|ISA directive search failed'
 'isa-comment-filter|rg|:[0-9]+:[[:space:]]*#|1|complete|ISA comment filtering failed'
 'isa-allowlist|rg|^\.cargo/config|1|complete|ISA allowlist filtering failed'
 'isa-target-search|rg|target_arch = "x86_64"|1|complete|rg isa-target-scope failed'
 'isa-build-late|rg|^\[build\]|1|empty|global build-table search failed'
)
for fault_case in "${fault_cases[@]}"; do
    IFS='|' read -r name tool match occurrence mode expected <<<"$fault_case"
    assert_fault_rejected "$name" "$tool" "$match" "$occurrence" "$mode" "$expected"
done

# Empty optional sections differ from an explicitly empty name: absence is valid, while a parsed
# empty [[bin]] name remains a policy violation. One required root may contain no package while
# the collective Cargo population remains nonempty.
no_sections="$scratch_root/no-sections"
create_valid_fixture "$no_sections"
sed -i '/^\[lib\]$/,/^\[features\]$/ { /^\[features\]$/!d; }' "$no_sections/crates/library/Cargo.toml"
bash "$policy_script" "$no_sections" >/dev/null

empty_root="$scratch_root/empty-root"
create_valid_fixture "$empty_root"
rm -rf -- "$empty_root/hosts/binary"
bash "$policy_script" "$empty_root" >/dev/null

mutate_empty_bin_name() { sed -i '/^\[\[bin\]\]$/,$ s/name = "binary"/name = ""/' "$1/hosts/binary/Cargo.toml"; }
expect_failure_with_message empty-bin-name 'bin name must be binary' mutate_empty_bin_name

for required_root in crates hosts tools sidecars; do
    missing="$scratch_root/missing-${required_root//\//-}"
    create_valid_fixture "$missing"
    if [[ "$required_root" == crates ]]; then
        # crates/math/LICENSE-libm.txt is itself part of the valid legal prelude, so an on-disk
        # missing crates/ cannot get past that earlier contract. Inject find's real missing-root
        # outcome after the valid prelude to exercise the otherwise unreachable discovery branch.
        shim="$scratch_root/shim-missing-crates"
        make_fault_shim "$shim" find 'crates hosts tools sidecars' 1 empty missing-crates
        output="$(WORKSPACE_FAULT_STATE="$shim/state" PATH="$shim:$PATH" bash "$policy_script" "$missing" 2>&1)" && rc=0 || rc=$?
    else
        rm -rf -- "$missing/$required_root"
        output="$(bash "$policy_script" "$missing" 2>&1)" && rc=0 || rc=$?
    fi
    [[ "$rc" -ne 0 && "$output" == *"find cargo-manifests failed"* ]] || {
        printf 'missing Cargo root was not a discovery failure: %s: %s\n' "$required_root" "$output" >&2; exit 1;
    }
done

collective_empty="$scratch_root/collective-empty"
create_valid_fixture "$collective_empty"
rm -rf -- "$collective_empty/crates/library" "$collective_empty/hosts/binary"
output="$(bash "$policy_script" "$collective_empty" 2>&1)" && rc=0 || rc=$?
[[ "$rc" -ne 0 && "$output" == *'Cargo manifest discovery returned an empty workspace'* ]] || {
    printf 'collective empty Cargo population had wrong result: %s\n' "$output" >&2; exit 1;
}

# Explicit repository mode covers the NUL-producing Git listing and an actual non-ignored nested
# manifest. The ordinary fixtures above cover exact non-repository fallback.
git_fixture="$scratch_root/git-positive"
create_valid_fixture "$git_fixture"
mkdir -p "$git_fixture/sdk/nested"
printf '%s\n' '[package]' 'name = "nested"' >"$git_fixture/sdk/nested/Cargo.toml"
git -C "$git_fixture" init -q
git -C "$git_fixture" add .
bash "$policy_script" "$git_fixture" >/dev/null

for isa_positive in empty comment-only; do
    isa_root="$scratch_root/isa-positive-$isa_positive"
    create_valid_fixture "$isa_root"
    mkdir -p "$isa_root/.cargo"
    if [[ "$isa_positive" == comment-only ]]; then
        printf '%s\n' '# target-feature and rustflags are documentation only' >"$isa_root/.cargo/config.toml"
    fi
    bash "$policy_script" "$isa_root" >/dev/null
done

invalid_git="$scratch_root/not-a-repository"
output="$(GIT_DIR="$invalid_git" bash "$policy_script" "$valid_root" 2>&1)" && rc=0 || rc=$?
[[ "$rc" -ne 0 && "$output" == *'git repository classification failed (status 128)'* ]] || {
    printf 'explicit GIT_DIR did not reject classification: %s\n' "$output" >&2; exit 1;
}

# Two disposable production mutations prove the same targeted assertions distinguish a swallowed
# producer/parser error from an ordinary checker rejection. Status 97 is reserved for the exact
# unexpected-success path in assert_fault_rejected.
production_policy="$policy_script"
mkdir -p "$scratch_root/mutants/scripts/lib"
cp "$script_directory/lib/gate.sh" "$scratch_root/mutants/scripts/lib/gate.sh"
population_mutant="$scratch_root/mutants/scripts/check-workspace-population-mutant.sh"
cp "$production_policy" "$population_mutant"
sed -i "s/(( CAPTURE_STATUS == 0 )) || execution_failure \"find \$label\" \"\$CAPTURE_STATUS\" \"\$CAPTURE_OUT\" \"\$CAPTURE_ERR\"/: # MUTANT swallow selected population failure/" "$population_mutant"
rg -qF ': # MUTANT swallow selected population failure' "$population_mutant" || {
    printf 'population mutant patch did not apply\n' >&2; exit 1;
}
policy_script="$population_mutant"
set +e
assert_fault_rejected mutant-population find 'crates hosts tools sidecars' 1 complete 'find cargo-manifests failed'
mutant_status=$?
set -e
[[ "$mutant_status" == 97 ]] || { printf 'population mutant assertion status %s, expected 97\n' "$mutant_status" >&2; exit 1; }

late_mutant="$scratch_root/mutants/scripts/check-workspace-late-mutant.sh"
cp "$production_policy" "$late_mutant"
sed -i "s/\*) execution_failure 'global build-table search' \"\$CAPTURE_STATUS\" \"\$CAPTURE_OUT\" \"\$CAPTURE_ERR\";;/*) : # MUTANT swallow selected late scan failure/" "$late_mutant"
rg -qF '*) : # MUTANT swallow selected late scan failure' "$late_mutant" || {
    printf 'late scan mutant patch did not apply\n' >&2; exit 1;
}
policy_script="$late_mutant"
set +e
assert_fault_rejected isa-build-late rg '^\[build\]' 1 empty 'global build-table search failed'
mutant_status=$?
set -e
[[ "$mutant_status" == 97 ]] || { printf 'late scan mutant assertion status %s, expected 97\n' "$mutant_status" >&2; exit 1; }
policy_script="$production_policy"
printf 'workspace production counter-mutants rejected by same assertions (status 97)\n'

# Keep the shared helper contract on the existing required-CI mutation entry point.
bash "$script_directory/test-gate-lib.sh" || exit "$?"

printf 'workspace policy mutation tests: ok\n'
